### ISSUE TITLE
Rare permission denied error when opening or manipulating worlds

### ISSUE THREAD

**Issue by Khroki** [Khroki/MCEdit-Unified#126]
![untitled](https://cloud.githubusercontent.com/assets/5132390/4869126/a3062d1c-6148-11e4-9132-5db997765067.png)
This happens rarely when opening a world too quickly after starting mcedit or sometimes when editing using larger brushes right after loading, going to call this one system specific unless someone confirms it, Windows 7.

**Comment by MythicalZ10n** [comment]
When I try to run MCEdit Unified on Linux, I come up with this error in terminal:

Starting MCEdit...
*** APP DIR: /home/mythicalz10n/MCEDITNEW/mcedit-1.5.4.1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 38, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 13, in <module>
  File "/tmp/release-master/MCEdit-Unified/splash.py", line 5, in <module>
  File "/tmp/release-master/MCEdit-Unified/directories.py", line 243, in <module>
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/mythicalz10n/.mcedit/MCEdit'
Press any key to close.

How do I fix this?
