### ISSUE TITLE
Attempting to run on Linux x64 -> TypeError: __init__() takes at least 2 positional arguments (1 given)

### ISSUE THREAD

**Issue by EvilSupahFly** [Khroki/MCEdit-Unified#285]
When running the newest version installed from the .RUN file on Linux (Ubuntu 14.04 x64), MCEdit (Unified) fails with the following error:
```
evilsupahfly@black-beast:~/mcedit$ python2 mcedit.pyc
Starting MCEdit...
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "mcedit.py", line 19, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/keys.py", line 2, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/__init__.py", line 12, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/shell.py", line 5, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/root.py", line 15, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/glbackground.py", line 21, in <module>
  File "openglwidgets.py", line 8, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/usr/lib/python2.7/dist-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)
```
Similarly, when running from the source cloned from GIT, I get the same error, but with slightly different pathnames listed:
```
evilsupahfly@black-beast:~/MCEdit-Unified-1.2.5.0$ python2 mcedit.py
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "mcedit.py", line 19, in <module>
    import keys
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/keys.py", line 2, in <module>
    import albow
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/albow/__init__.py", line 12, in <module>
    from albow.shell import Shell
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/albow/shell.py", line 5, in <module>
    from root import RootWidget
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/albow/root.py", line 15, in <module>
    from glbackground import *
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/glbackground.py", line 21, in <module>
    from albow.openglwidgets import GLOrtho
  File "/home/evilsupahfly/MCEdit-Unified-1.2.5.0/albow/openglwidgets.py", line 8, in <module>
    from OpenGL import GL, GLU
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/usr/lib/python2.7/dist-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)
```
Is there something I'm missing still? If more information on my system and the running environment is needed, let me know and I'll post everything I can.
```
OS: Ubuntu 14.04
uname -a results: Linux black-beast 3.18.1-031801-generic #201412170637 SMP Wed Dec 17 11:38:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Display Driver: official nvidia binary 340.xx series
```

**Comment by LaChal** [comment]
Accroding to the tracebacks you gave, it looks like your OpebGL for python is outdated.
You should have version 3+ installed.

Did you let the installer check for the dependencies, and did it upgrade OpenGL?

**Comment by EvilSupahFly** [comment]
I did, and it said everything was current (**PyOpenGL (3.0.2)**). I even checked with pip:
```
evilsupahfly@black-beast:~$ pip list
adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
argparse (1.2.1)
arrow (0.5.0)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
compizconfig-python (0.9.11.3)
Cython (0.20.1post0)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
distro-info (0.12)
docutils (0.11)
duplicity (0.6.23)
euca2ools (3.0.1)
html5lib (0.999)
httplib2 (0.8)
ipython (1.2.1)
Jinja2 (2.7.2)
lockfile (0.8)
lxml (3.3.3)
MarkupSafe (0.18)
numpy (1.8.2)
oauthlib (0.6.1)
oneconf (0.3.7)
PAM (0.4.2)
Patool (1.4)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
pyclamav (0.4.1)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygame (1.9.1release)
Pygments (1.6)
pygobject (3.12.0)
pyinotify (0.9.4)
PyOpenGL (3.0.2)
PyOpenGL-accelerate (3.1.0)
pyOpenSSL (0.13)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-dateutil (2.4.0)
python-debian (0.1.21-nmu2ubuntu2)
python-xlib (0.14)
pytools (2013.5.7)
pyxdg (0.25)
PyYAML (3.10)
pyzmq (14.0.1)
reportlab (3.0)
requestbuilder (0.1.0-beta1)
requests (2.2.1)
roman (2.0.0)
sessioninstaller (0.0.0)
setuptools (3.3)
simplegeneric (0.8.1)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
Sphinx (1.2.2)
ssh-import-id (3.21)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
ubuntu-tweak (0.8.8)
unity-lens-photos (1.0)
urllib3 (1.7.1)
wsgiref (0.1.2)
xdiagnose (3.6.3build2)
youtube-dl (2015.01.30.2)
zeitgeist-explorer (0.2)
zope.interface (4.0.5)
```
On a whim, I uninstalled and reinstalled PyOpenGL, and now pip reports it as version 3.1.0, which seems to resolve the issue. Perhaps the README can be updated with specific version requirements?

**Comment by Calendis** [comment]
Just encountered this issue myself. Repository had 3.0.2, which did not work, but pip3 had 3.1.0. I am thankful for this issue
