### ISSUE TITLE
MCEdit gets stuck/freezes in OS X Yosemite

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [Khroki/MCEdit-Unified#331]
This happened exactly the same way with an older version of this app from around December.  Trying to open the `level.dat` file from the folder Airship Battles using the open button causes the thing to freeze.  It turns green and flashes white and green every time you move the mouse, nothing can be done.  The folder is 19MB despite being a boat in a void world, it is a year old so I think it could be corrupted.  I tried the first two folders from here https://github.com/msalihov/ParaPGM-Maps

Trying Avalon Funland gives the usual MCEdit error.

2015-03-08 8:27:00.008 PM mcedit[2737]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
2015-03-08 8:27:02.883 PM mcedit[2737]: Minecraft_Server.jar storage initialized.
2015-03-08 8:27:02.883 PM mcedit[2737]: Each server is stored in a subdirectory of /Users/carlarogers/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
2015-03-08 8:27:02.883 PM mcedit[2737]: Cached servers:  []
2015-03-08 8:27:17.932 PM mcedit[2737]: Open File
2015-03-08 8:27:18.540 PM mcedit[2737]: assertion failed: 14C109: libxpc.dylib + 97940 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x89
2015-03-08 8:27:23.061 PM com.apple.xpc.launchd[1]: (com.apple.quicklook[2750]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
2015-03-08 8:27:24.480 PM mcedit[2737]: [   ERROR][                   root.py:926]:Wasn't able to open a file {file => /Users/carlarogers/GitHub/OCN-Maps/Airship Battle/level.dat}
2015-03-08 8:27:24.481 PM mcedit[2737]: Traceback (most recent call last):
2015-03-08 8:27:24.481 PM mcedit[2737]:   File "leveleditor.pyc", line 923, in loadFile
2015-03-08 8:27:24.481 PM mcedit[2737]:   File "pymclevel/mclevel.pyc", line 216, in fromFile
2015-03-08 8:27:24.481 PM mcedit[2737]:   File "pymclevel/infiniteworld.pyc", line 1084, in __init__
2015-03-08 8:27:24.481 PM mcedit[2737]: AssertionError: Pre-Anvil world formats are not supported (for now)
2015-03-08 8:27:31.729 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.000730
2015-03-08 8:27:38.000 PM kernel[0]: Sandbox: mdworker(2282) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:38.000 PM kernel[0]: Sandbox: mdworker(2282) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:38.799 PM mdworker[2282]: CGSConnectionByID: 0 is not a valid connection ID.
2015-03-08 8:27:38.800 PM mdworker[2282]: Invalid Connection ID 0
2015-03-08 8:27:43.000 PM kernel[0]: Sandbox: mdworker(2285) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:43.000 PM kernel[0]: Sandbox: mdworker(2285) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:43.620 PM mdworker[2285]: CGSConnectionByID: 0 is not a valid connection ID.
2015-03-08 8:27:43.620 PM mdworker[2285]: Invalid Connection ID 0
2015-03-08 8:27:44.000 PM kernel[0]: Sandbox: mdworker(2284) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:44.000 PM kernel[0]: Sandbox: mdworker(2284) deny mach-lookup com.apple.nsurlstorage-cache
2015-03-08 8:27:44.758 PM mdworker[2284]: CGSConnectionByID: 0 is not a valid connection ID.
2015-03-08 8:27:44.759 PM mdworker[2284]: Invalid Connection ID 0
2015-03-08 8:28:52.122 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.002187
2015-03-08 8:28:59.748 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.000279
2015-03-08 8:29:08.421 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.002599
2015-03-08 8:29:21.115 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.000048
2015-03-08 8:29:54.872 PM mcedit[2767]: Splash load...
2015-03-08 8:29:56.102 PM mcedit[2767]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.10.2. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2015-03-08 8:29:56.102 PM mcedit[2767]: 0   CarbonCore                          0x00007fff92c0fd9b ___Gestalt_SystemVersion_block_invoke + 113
2015-03-08 8:29:56.103 PM mcedit[2767]: 1   libdispatch.dylib                   0x00007fff913b8c13 _dispatch_client_callout + 8
2015-03-08 8:29:56.103 PM mcedit[2767]: 2   libdispatch.dylib                   0x00007fff913b8b26 dispatch_once_f + 117
2015-03-08 8:29:56.103 PM mcedit[2767]: 3   CarbonCore                          0x00007fff92bb83ca _Gestalt_SystemVersion + 987
2015-03-08 8:29:56.103 PM mcedit[2767]: 4   CarbonCore                          0x00007fff92bb7fb7 Gestalt + 144
2015-03-08 8:29:56.103 PM mcedit[2767]: 5   SDL                                 0x0000000104412d38 SDL_SoftStretch + 14284
2015-03-08 8:29:56.103 PM mcedit[2767]: 6   SDL                                 0x0000000104408627 SDL_VideoInit + 531
2015-03-08 8:29:56.846 PM mcedit[2767]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
2015-03-08 8:30:02.732 PM mcedit[2767]: Minecraft_Server.jar storage initialized.
2015-03-08 8:30:02.732 PM mcedit[2767]: Each server is stored in a subdirectory of /Users/carlarogers/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
2015-03-08 8:30:02.733 PM mcedit[2767]: Cached servers:  []
2015-03-08 8:30:11.629 PM mcedit[2767]: Open File
2015-03-08 8:30:13.354 PM mcedit[2767]: assertion failed: 14C109: libxpc.dylib + 97940 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x89
2015-03-08 8:30:16.848 PM com.apple.xpc.launchd[1]: (com.apple.quicklook[2779]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
2015-03-08 8:30:20.561 PM mcedit[2767]: [   ERROR][                   root.py:728]:MCEdit version Unified v1.3.0.0 for Minecraft 1.8
2015-03-08 8:30:20.564 PM mcedit[2767]: Traceback (most recent call last):
2015-03-08 8:30:20.564 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 767, in <module>
2015-03-08 8:30:20.564 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 726, in main
2015-03-08 8:30:20.564 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 560, in main
2015-03-08 8:30:20.565 PM mcedit[2767]:   File "albow/root.pyc", line 158, in run
2015-03-08 8:30:20.565 PM mcedit[2767]:   File "albow/root.pyc", line 223, in run_modal
2015-03-08 8:30:20.565 PM mcedit[2767]:   File "albow/widget.pyc", line 747, in gl_draw_all
2015-03-08 8:30:20.567 PM mcedit[2767]:   File "albow/widget.pyc", line 747, in gl_draw_all
2015-03-08 8:30:20.567 PM mcedit[2767]:   File "albow/widget.pyc", line 747, in gl_draw_all
2015-03-08 8:30:20.568 PM mcedit[2767]:   File "albow/widget.pyc", line 747, in gl_draw_all
2015-03-08 8:30:20.568 PM mcedit[2767]:   File "albow/widget.pyc", line 744, in gl_draw_all
2015-03-08 8:30:20.568 PM mcedit[2767]:   File "albow/openglwidgets.pyc", line 22, in gl_draw_self
2015-03-08 8:30:20.568 PM mcedit[2767]:   File "albow/openglwidgets.pyc", line 28, in gl_draw_viewport
2015-03-08 8:30:20.568 PM mcedit[2767]:   File "viewports/camera.pyc", line 1340, in gl_draw
2015-03-08 8:30:20.569 PM mcedit[2767]:   File "viewports/camera.pyc", line 1355, in render
2015-03-08 8:30:20.569 PM mcedit[2767]:   File "renderer.pyc", line 2995, in draw
2015-03-08 8:30:20.569 PM mcedit[2767]:   File "glutils.pyc", line 198, in bind
2015-03-08 8:30:20.569 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
2015-03-08 8:30:20.569 PM mcedit[2767]: GLError: GLError(
2015-03-08 8:30:20.569 PM mcedit[2767]: 	err = 1282,
2015-03-08 8:30:20.570 PM mcedit[2767]: 	description = 'invalid operation',
2015-03-08 8:30:20.570 PM mcedit[2767]: 	baseOperation = glBindTexture,
2015-03-08 8:30:20.570 PM mcedit[2767]: 	cArguments = (GL_TEXTURE_2D, 3L)
2015-03-08 8:30:20.570 PM mcedit[2767]: )
2015-03-08 8:30:20.570 PM mcedit[2767]: Traceback (most recent call last):
2015-03-08 8:30:20.571 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
2015-03-08 8:30:20.571 PM mcedit[2767]:     _run()
2015-03-08 8:30:20.571 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
2015-03-08 8:30:20.572 PM mcedit[2767]:     exec(compile(source, path, 'exec'), globals(), globals())
2015-03-08 8:30:20.572 PM mcedit[2767]:   File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 776, in <module>
2015-03-08 8:30:20.572 PM mcedit[2767]:     raw_input("Press the Enter key to close this window")
2015-03-08 8:30:20.572 PM mcedit[2767]: EOFError: EOF when reading a line
2015-03-08 8:30:20.572 PM mcedit[2767]: ==================================
2015-03-08 8:30:20.573 PM mcedit[2767]: 			  MCEdit has crashed
2015-03-08 8:30:20.573 PM mcedit[2767]: ==================================
2015-03-08 8:30:20.741 PM mcedit[2767]: mcedit Error
2015-03-08 8:30:20.741 PM mcedit[2767]: 2015-03-08 20:30:20.741 mcedit[2767:77783] mcedit Error
2015-03-08 8:30:26.986 PM mds[37]: (DiskStore.Normal:2376) 7e001 1.000115
2015-03-08 8:30:28.581 PM mcedit[2767]: Press the Enter key to close this window
2015-03-08 8:30:28.817 PM Console[2783]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable

**Comment by Khroki** [comment]
From what we can tell this is due to some incompatibility with the new webkit, our renderer, Xquartz, and OSX v10.10.x somehow opengl isn't being handed back to mcedit properly under 3 views. We weren't able to fix 2 of the views but we've improved the old Albow file chooser and the next build will include it. It's not ideal but it works. If we do find a fix/someone submits one we'll happily add the built in file chooser back. We're not sure what changed, but we suspect it's apple's fault. In the mean time one of the two middle views works.

**Comment by CoWinkKeyDinkInc** [comment]
What is the two middle views?

**Comment by Khroki** [comment]
The column and Icon views, in 1.3.0.0 I think only the column view works.
