### ISSUE TITLE
mcedit crashes on startup

### ISSUE THREAD

**Issue by AlexNova1555** [Khroki/MCEdit-Unified#360]
When i open my mcedit its just crash and i got an error

http://pastebin.com/KXiaz6Q8

i try to delete and download a new one but still it didnt work

MCEdit Version Number: 1.3.1.0

Minecraft Version Number: 1.8.1

Operating System Version: windows 7 ultimate sp1 64 bit

full log: http://pastebin.com/CJar6Ph9

**Comment by codewarrior0** [comment]
Go to your Documents folder, open the MCEdit folder, and throw away the `mcedit.ini` file. It must have been damaged by a different version of MCEdit.

**Comment by AlexNova1555** [comment]
OK now its works tnx !

**Comment by dylandarko7** [comment]
MCEdit won't let me edit a world it says this:MCEdit version: 2.0.0-beta14
Python version: 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
Platform: darwin
System version: Darwin-18.7.0-x86_64-i386-64bit
Processor: i386

Obtained a GL context with this format:
Valid: True
Version: 1.0
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.NoProfile

Driver info:
GL_VERSION: 2.1 INTEL-12.10.12 (2, 1)
GL_VENDOR: 'Intel Inc.'
GL_RENDERER: 'Intel(R) Iris(TM) Graphics 6100'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2/editorsession.py", line 1643, in viewOffsetChanged (self is a EditorTab)
  File "mcedit2/worldview/minimap.py", line 187, in currentViewMatrixChanged (self is a MinimapWorldView)
  File "mcedit2/util/raycast.py", line 30, in rayCastInBounds  
  File "mcedit2/util/profiler.py", line 73, in _wrapper (self is a Profiler)
  File "mcedit2/util/raycast.py", line 77, in rayCast  
  File "mcedit2/util/raycast.py", line 215, in advanceToChunk  
  File "mceditlib/worldeditor.py", line 831, in getChunk (self is a WorldEditorDimension)
  File "mceditlib/worldeditor.py", line 499, in getChunk (self is a WorldEditor)
  File "mceditlib/cachefunc.py", line 77, in __call__  
  File "mceditlib/worldeditor.py", line 477, in _getChunkDataRaw (self is a WorldEditor)
  File "mceditlib/anvil/adapter.py", line 922, in readChunk (self is a AnvilWorldAdapter)
AnvilChunkFormatError: [Errno Error loading chunk: KeyError('Key Blocks not found.',)] None: <traceback object at 0x12cac92d8>
