### ISSUE TITLE
Analyze exception: "Item not found", different behavior requested

### ISSUE THREAD

**Issue by Geethebluesky** [Khroki/MCEdit-Unified#367]
I get an exception when I attempt to run the Analyze function on a modded world. 

I feel the program should be able to handle unknown items by listing them as <Unknown> instead of refusing to provide the list entirely.
Console log provided at the bottom.

Steps:
Select chunks using leftmost Selection tool in Camera view
Click Analyze 

Tried on Windows 7, MCedit Unified 1.3.1.0 64 bits, world is from Minecraft version 1.7.1.0 with following mods:

additionalpipes-4.2.1.jar
AdminCommandsToolbox-0.0.2a_1.7.10.jar
AppleCore-mc1.7.10-1.1.0.jar
backpack-2.0.1-1.7.x.jar
BetterAnvil-3.1.8.jar
BetterFoliage-mc1.7-1.0.10.jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
buildcraft-6.4.11.jar
buildcraft-compat-6.4.2.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.17-universal.jar
ChocoCraft-4.1.5.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
coralmod-1.7.10-3.141.jar
coroutil-1.1.2 for MC v1.7.10.jar
CraftGuide-1.6.8.1.zip
customrecipes-1.7.10-4.7.jar
DrZharks MoCreatures Mod v6.3.1.zip
ExtraDoors-1.7.2 (and 1.7.10)-1.5.1.jar
fastcraft-1.21.jar
Highlands-1.7.10-v-2.2.3.jar
JustAnotherSpawner-0.16.18.jar
LycanitesMobsComplete 1.10.13.1 [1.7.10].jar
matmos
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
NBTEdit_1.7.10.jar
OpenEye-0.6-1.7.10.jar
OptiFine_1.7.10_HD_U_B5.jar
Pam's Clay Spawn 1.7.2a works with 10.zip
Pam's HarvestCraft 1.7.10h.jar
Pam's Simple Recipes 1.7.2a works with 10.zip
Ruins-1.7.10.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
StalkerCreepers-1.7.10.jar
UpdateCheckerMod-1.7.10.jar
VoxelMods
Weather-2.3.7.jar
WildCaves3-0.4.3.7(1.7.10).jar
ZombieAwareness-1.9.6.jar
[1.7.10] Doggy Talents - v1.9.0f.zip
[1.7.10]FloatingRuins-universal-1.7.10.r02.jar
[1.7.10]StartingInventory-universal-1.7.10.r03.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
[1.7.2 and 1.7.10] ChickenShed (v1.1.3).jar

Console log below.

Splash load...
Running in fixed mode. Support files are in your Documents folder.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of O:\__Users\XXXXXXXXXX\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  []
[   ERROR][                  root.py:1596]:Exception:
Traceback (most recent call last):
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\mceutils", line 50, in _alertException
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.select", line 1121, in analyzeSelection
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\leveleditor", line 542, in analyzeBox
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\mceutils", line 702, in showProgress
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 520, in present
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 224, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 758, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 765, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 329, in draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\mceutils", line 616, in draw  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\leveleditor", line 534, in _analyzeBox
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\pymclevel.items", line 64, in findItem
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\pymclevel.items", line 82, in findItemID ItemNotFound

**Comment by TrazLander** [comment]
Kinda amazed it was able to open the world at all.

**Comment by Geethebluesky** [comment]
It's half-behaving at least :)

**Comment by naor2013** [comment]
Fixed, now will show as "Unknown Item"
(I didn't test it since I don't use mods, so please tell us if it's fixed for you when we'll release)
Thanks for the report
