### ISSUE TITLE
[Linux] AttributeError On startup

### ISSUE THREAD

**Issue by FrozenPigs** [Khroki/MCEdit-Unified#378]
I have been trying to get mcedit to work but it hasnt quite been working out for me. This laptop is running arch linux and I'm pretty sure I got all the deps installed. All that happens is the splash screen comes up then crashes.
```
> $ ./mcedit.sh                                                                                                                                 [±master]
Starting MCEdit...
Splash load...
Running in fixed mode. Support files are in your Documents folder.
*** Xlib version 0.14 found in user's libraries.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/wednesday/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Xlib.protocol.request.QueryExtension
[   ERROR][                   root.py:764]:MCEdit version Unified v1.3.2.0 for Minecraft 1.8
Traceback (most recent call last):
  File "mcedit.py", line 803, in <module>
    main(sys.argv)
  File "mcedit.py", line 762, in main
    MCEdit.main()
  File "mcedit.py", line 478, in main
    displayContext = GLDisplayContext(splash.splash)
  File "/home/wednesday/mcedit/MCEdit-Unified/utilities/gl_display_context.py", line 21, in __init__
    self.reset(splash)
  File "/home/wednesday/mcedit/MCEdit-Unified/utilities/gl_display_context.py", line 92, in reset
    windowIDs = root.get_full_property(dis.intern_atom('_NET_CLIENT_LIST'), mcplatform.Xlib.X.AnyPropertyType).value
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by LaChal** [comment]
Can you paste here the `mcedit.log` part concerning the platform information?
It's on top of the log file.

**Comment by FrozenPigs** [comment]
Here ya go.
```
[   DEBUG][         albow.translate.py:65]:*** Platform information
[   DEBUG][         albow.translate.py:66]:    System: Linux
[   DEBUG][         albow.translate.py:67]:    Release: 3.19.3-3-ARCH
[   DEBUG][         albow.translate.py:68]:    Version: #1 SMP PREEMPT Wed Apr 8 14:10:00 CEST 2015
[   DEBUG][         albow.translate.py:69]:    Architecture: 64bit, ELF
[   DEBUG][         albow.translate.py:70]:    Dist: , , 
[   DEBUG][         albow.translate.py:71]:    Machine: x86_64
[   DEBUG][         albow.translate.py:72]:    Processor: 
[   DEBUG][         albow.translate.py:73]:    Locale: en_US
[   DEBUG][         albow.translate.py:74]:    Encoding: UTF-8
[   DEBUG][         albow.translate.py:94]:    numpy version: 1.9.2
[   DEBUG][         albow.translate.py:94]:    pygame version: 1.9.1release
[   DEBUG][         albow.translate.py:94]:    OpenGL version: 3.1.0
[   DEBUG][         albow.translate.py:95]:***
[   ERROR][                   root.py:764]:MCEdit version Unified v1.3.2.0 for Minecraft 1.8
```

**Comment by LaChal** [comment]
Everything seem to be allright, except the `Dist` output. But it's not very significative.

Did you try to reinstall MCEdit?

**Comment by FrozenPigs** [comment]
I just did and got the same.

**Comment by LaChal** [comment]
Looks like your Linux window manager returns nothing on a `_NET_CLIENT_LIST` query.

As a work arround for this, you can try to download the `gl_display_context.py` file of the commit 3decb2e302, and put it in the `utilities` folder of your MCEdit installation. Rename the `gl_display_context.pyc` file before running MCEdit, or it will be overwritten.

**Comment by FrozenPigs** [comment]
Well that has seemed to fix the issue I was having but now a new one has shown itself.
```
An error occurred checking for updates.
[   ERROR][                   root.py:754]:MCEdit version Unified v1.3.2.0 for Minecraft 1.8
Traceback (most recent call last):
  File "../bin3/mcedit/mcedit.py", line 793, in <module>
  File "../bin3/mcedit/mcedit.py", line 752, in main
  File "../bin3/mcedit/mcedit.py", line 551, in main
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/dialogs.py", line 161, in ask
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/widget.py", line 550, in present
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/root.py", line 230, in run_modal
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/widget.py", line 798, in gl_draw_all
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/widget.py", line 798, in gl_draw_all
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/widget.py", line 795, in gl_draw_all
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/albow/file_opener.py", line 102, in gl_draw_self
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/leveleditor.py", line 1513, in drawStars
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/viewports/camera.py", line 234, in setModelview
  File "/usr/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
NullFunctionError: Attempt to call an undefined function gluLookAt, check for bool(gluLookAt) before calling
```

**Comment by LaChal** [comment]
Your openGL install seem to be uncompliant. You may verify it and its dependencies.

Are you running a beta version of ARCH Linux?

**Comment by FrozenPigs** [comment]
I dont think so but I am using a pick and mix of stable and unstable packages.

**Comment by LaChal** [comment]
It may be the cause of the crashes you experience.

I'll install an ARCH Linux and have a try.

**Comment by AdmiralMemo** [comment]
FrozenPigs: If you're having issues with gl_display_context.py, it was mentioned in https://github.com/Khroki/MCEdit-Unified/issues/365 that an issue might have to do with windows that have "strange characters" in their title bars. Can you close those windows and see if the problem goes away? (In my case, it was Skype having ™ in the title bar.)
