### ISSUE TITLE
OS X, Will not start if Application installed by another user

### ISSUE THREAD

**Issue by softgrow** [Khroki/MCEdit-Unified#471]
The application will not start, console shows

    15/08/2015 11:55:25.619 am mcedit[4558]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
    15/08/2015 11:55:26.224 am mcedit[4558]: Splash load...
    15/08/2015 11:55:26.690 am mcedit[4558]: Traceback (most recent call last):
    15/08/2015 11:55:26.690 am mcedit[4558]:   File "/Applications/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
    15/08/2015 11:55:26.690 am mcedit[4558]:     _run()
    15/08/2015 11:55:26.690 am mcedit[4558]:   File "/Applications/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
    15/08/2015 11:55:26.690 am mcedit[4558]:     exec(compile(source, path, 'exec'), globals(), globals())
    15/08/2015 11:55:26.690 am mcedit[4558]:   File "/Applications/mcedit.app/Contents/Resources/mcedit.py", line 13, in <module>
    15/08/2015 11:55:26.691 am mcedit[4558]:     import splash
    15/08/2015 11:55:26.691 am mcedit[4558]:   File "splash.pyc", line 49, in <module>
    15/08/2015 11:55:26.691 am mcedit[4558]: IOError: [Errno 13] Permission denied: u'/Applications/mcedit.app/Contents/Resources/splash'
    15/08/2015 11:55:26.755 am mcedit[4558]: mcedit Error

# To reproduce
1. Download installation zip file
2. Copy Application package from the zip file to Applications Folder
3. Log in as a different user, not the user that installed it
4. Start the application

# Workaround
1. Open command shell as an Administrator
2. ```touch /Applications/mcedit.app/Contents/Resources/splash```
3. ```chmod o+w /Applications/mcedit.app/Contents/Resources/splash```

**Comment by Khroki** [comment]
Hmm, looks like the splash folder is being generated with the first user's permissions.

**Comment by Estevo-Aleixo** [comment]
Where in code is the splash directory created?

**Comment by LaChal** [comment]
The `splash` folder is not created at runtime. It is embeded in the application during the compilation, AFAIK. (I'm not the one who compiles on Mac, but this is done like this on Linux and Windows.)

By the way, OSX is derived from a Unix system (actually BSD), and may not parmit a user to access other users apps/data. Depending the policies, Windows can behave like this too.

IMO, this is not a MCEdit bug, but an OS side issue, due to the structure of the OS and its security policies.

**Comment by codewarrior0** [comment]
> IMO, this is not a MCEdit bug, but an OS side issue, due to the structure of the OS and its security policies.

[Yet, here you are writing to files inside the application bundle.](https://github.com/Khroki/MCEdit-Unified/blob/master/splash.py#L49)

**Comment by LaChal** [comment]
So, I'm sure you have the solution.

**Comment by codewarrior0** [comment]
Yep. It's `Don't write files inside the application bundle.`

**Comment by LaChal** [comment]
This is obvious.

But with 'solution', I meant a code piece wich can permit a Mac user to run MCEdit without delaying the splash display, without workaround and without installing the app for another user.
I can't do this, because I don't have a Mac...

**Comment by codewarrior0** [comment]
You should be able to solve this. The same problem is present on Linux if the user has no write permission to the file given by `splash_name`.

**Comment by LaChal** [comment]
On Linux the user is the owner of the application directory, and other users will not be able to run MCEdit for the reason they can't... this is the base policy on these systems.
Moreover, Linux users are warned at install time that MCEdit is installed for the current user only.

**Comment by codewarrior0** [comment]
Yes. That is the same problem. If you can't solve it, then you will have to also warn OS X users that MCEdit is installed for the current user only.

**Comment by Estevo-Aleixo** [comment]
sed 's/directories.getDataDir()/directories.docsFolder/' splash.py

**Comment by codewarrior0** [comment]
Better yet, don't even write the file at all. It serves no purpose.

**Comment by LaChal** [comment]
If not present, the file is re-created. Look at readme (and the source) for more information.

Another idea is to change the app rights bits to permit other users to read/write/execute it, and link it in the other users Application folder.

**Comment by codewarrior0** [comment]
Yes, I read the source. The file does nothing. Just don't write it.

**Comment by LaChal** [comment]
The file contains the name of the splash to be used. This name is changed everytime MCEdit starts.

**Comment by codewarrior0** [comment]
The file is written but never read.

Regardless, it was an incredibly bad decision to write a file to the application folder to begin with. That is basically the first rule of writing apps for multi-user systems: *Do not write files to the application folder. You may not have permission to write files to the application folder.*

**Comment by LaChal** [comment]
> The file is written but never read.

Right. Someone disabled it: https://github.com/Khroki/MCEdit-Unified/commit/02d7683d69c2b9a31b7c51d6482f26fb8dcde47c
It will be reenabled.

**Comment by Khroki** [comment]
Would it be possible to have that file written with other support files (such as the usercache) instead of inside the .app? That would also make it easier for users to add their own splashes if they so desired.

**Comment by cleverca22** [comment]
i also ran into a similar problem, mcedit.log is saved to the read-only application folder and crashes it

**Comment by LaChal** [comment]
As said, OSX is a Unix based system and have some policies regarding using other users stuff.
I recommend to install MCEdit for each user who want to use it on the machine.
