### ISSUE TITLE
Error with not generated chunks selection

### ISSUE THREAD

**Issue by amauryvallier** [Khroki/MCEdit-Unified#482]
I just had a little problem trying to reduce my world size by deleting chunks with MCEdit. It seems that not generated chunks selection causes an error. I don't think it is normal as I remember clearly having done the same thing without problem with a previous version of MCEdit.
	
**Steps to reproduce :**
1. Open a world with MCEdit
2. Try to select chunks and make your selection go "beyond the limits" of the world that is to say have not generated chunks as part of the selection (that's easier to visualise in Chunk View)
3. Watch as MCEdit closes itself with a nice "TypeError: 'NoneType' object is not iterable"
	
**Minecraft Version Number :** Vanilla 1.8.8 (tested with a world created in 1.5 but converted and another created in 1.7 but updated too)
**MCEdit Version Number :** 1.4.0.1 (MCEdit version Unified v1.4.0.1 for Minecraft 1.8/1.9)
**Operating System Version :** Windows 10 Family 64-bit

**Error Log :**
[   ERROR][                  root.py:1601]:MCEdit version Unified v1.4.0.1 for Minecraft 1.8/1.9
[   ERROR][                  root.py:1601]:'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 774, in main
  File "<string>", line 629, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 168, in run
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 233, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 783, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 22, in gl_draw_self
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 28, in gl_draw_viewport
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1818, in gl_draw
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1845, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 583, in update_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 569, in show_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1617, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.chunk", line 195, in worldTooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.select", line 721, in selectionBoxInProgress
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.editortool", line 259, in selectionBoxForCorners
TypeError: 'NoneType' object is not iterable

**Comment by bauwks** [comment]
I'm seeing this as well.  It definitely used to work in 1.3.3.0

**Comment by TropicSapling** [comment]
This has happened to me too.

**Comment by naor2013** [comment]
Fixed for next release
