### ISSUE TITLE
Chunk Selection Tool Crash

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#487]
When selecting chunks with the chunk control tool and a box is selected starting inside the generated terrain and the mouse is moved into un-generated chunks (possibly just corners of un-generated chunks) MCedit will crash and give a NoneType is not iterable error.

Crash:
[   ERROR][                  root.py:1601]:MCEdit version Unified v1.4.0.1 for Minecraft 1.8/1.9
[   ERROR][                  root.py:1601]:'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 774, in main
  File "<string>", line 629, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 168, in run
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 233, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 783, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 22, in gl_draw_self
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 28, in gl_draw_viewport
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1818, in gl_draw
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 81, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1845, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 583, in update_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 569, in show_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 85, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1617, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.chunk", line 195, in worldTooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.select", line 721, in selectionBoxInProgress
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.editortool", line 259, in selectionBoxForCorners
TypeError: 'NoneType' object is not iterable
Press RETURN or close this window to dismiss.

**Comment by naor2013** [comment]
Already fixed for next release but thanks for the report!
