### ISSUE TITLE
Dragging a selection box out of existing chunks when in Chunk Control mode will crash MCEdit

### ISSUE THREAD

**Issue by haukepribnow** [Khroki/MCEdit-Unified#507]
When moving the mouse cursor to a nonexisting chunk while selecting some chunks in Chunk Control mode, MCEdit crashes.

Example: I started selecting some chunks as visible on this screenshot:
![image](https://cloud.githubusercontent.com/assets/811850/10143908/1900c6f8-661b-11e5-8d00-7ae9610fa162.png)

When moving the cursor outside of the area of existing chunks, MCEdit crashes.

Here's the first stack trace:

```
[   ERROR][                  root.py:1601]:'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 774, in main
  File "<string>", line 629, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 168, in run
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 233, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 783, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 22, in gl_draw_self
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 28, in gl_draw_viewport
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1818,in gl_draw
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 81, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1845, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 583, in update_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 569, in show_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 85, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1617, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.chunk", line 195, in worldTooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.select", line 721, in selectionBoxInProgress
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.editortool", line 259, in selectionBoxForCorners
TypeError: 'NoneType' object is not iterable
Press RETURN or close this window to dismiss.
```

And this is the second stack trace after pressing return:

```
Traceback (most recent call last):
  File "<string>", line 815, in <module>
  File "<string>", line 774, in main
  File "<string>", line 629, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 168, in run
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 233, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 783, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 22, in gl_draw_self
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 28, in gl_draw_viewport
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1818, in gl_draw
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 81, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1845, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 583, in update_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 569, in show_tooltip
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.chunk", line 85, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1617, in tooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.chunk", line 195, in worldTooltipText
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.select", line 721, in selectionBoxInProgress
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.editortool", line 259, in selectionBoxForCorners
TypeError: 'NoneType' object is not iterable

==================================
                          MCEdit has crashed
==================================
Press the Enter key to close this window
```

**Comment by naor2013** [comment]
Fixed already for next release
Thanks for the report
