### ISSUE TITLE
ok so this is the error i get does anyone else have this issue

### ISSUE THREAD

**Issue by death2056** [Khroki/MCEdit-Unified#514]
MCEdit version: 2.0.0alpha-767
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-post2012Server-6.3.9600
Processor: AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD

Obtained a GL context with this format:
Valid: True
Version: 4.3
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.3.12682 Compatibility Profile Context 13.302.1101.1004 (4, 3)
GL_VENDOR: 'ATI Technologies Inc.'
GL_RENDERER: 'AMD Radeon(TM) R2 Graphics'

------

Unhandled Exception

Traceback (most recent call last):
  File "<string>", line 207, in <module>  
  File "<string>", line 203, in main  
  File "out00-PYZ.pyz\mcedit2.util.profiler", line 66, in _wrapper (self is a Profiler)
  File "<string>", line 177, in startup  
  File "out00-PYZ.pyz\mcedit2.editorapp", line 282, in __init__ (self is a MCEditApp)
  File "out00-PYZ.pyz\mcedit2.worldlist", line 211, in __init__ (self is a WorldListWidget)
  File "out00-PYZ.pyz\mcedit2.worldlist", line 305, in reloadList (self is a WorldListWidget)
  File "out00-PYZ.pyz\mcedit2.worldlist", line 342, in showWorld (self is a WorldListWidget)
  File "out00-PYZ.pyz\mcedit2.worldview.minimap", line 152, in __init__ (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 149, in __init__ (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 190, in setDimension (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 228, in createSceneGraph (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.worldview.minimap", line 161, in createWorldScene (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.worldview.worldview", line 224, in createWorldScene (self is a MinimapWorldView)
  File "out00-PYZ.pyz\mcedit2.rendering.worldscene", line 222, in __init__ (self is a WorldScene)
  File "out00-PYZ.pyz\mcedit2.rendering.worldscene", line 76, in __init__ (self is a SceneUpdateTask)
  File "out00-PYZ.pyz\mceditlib.worldeditor", line 713, in blocktypes (self is a WorldEditorDimension)
  File "out00-PYZ.pyz\mceditlib.worldeditor", line 415, in blocktypes (self is a WorldEditor)
AttributeError: 'AnvilWorldAdapter' object has no attribute 'blocktypes'

**Comment by codewarrior0** [comment]
Fixed in 9ec45459c73215afbc8dd4ecf676a25e3e7afc0f

**Comment by naor2013** [comment]
It's not the place to write MCEdit2 issues, just Unified ones but it seems like CodeWarrior fixed it in MCEdit2 already :)

**Comment by codewarrior0** [comment]
Oh geez, I didn't even notice. :pig:
