### ISSUE TITLE
crash moving player

### ISSUE THREAD

**Issue by piersh** [Khroki/MCEdit-Unified#525]
Caught value error while getting player info for 1377740d-e96d-3851-89b2-9cf6091ac3d8
[   ERROR][                  root.py:1601]:MCEdit version Unified v1.4.0.1 for Minecraft 1.8/1.9
[   ERROR][                  root.py:1601]:'Player'
Traceback (most recent call last):
  File "<string>", line 774, in main
  File "<string>", line 629, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 168, in run
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.root", line 233, in run_modal
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 786, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.widget", line 783, in gl_draw_all
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 22, in gl_draw_self
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\albow.openglwidgets", line 28, in gl_draw_viewport
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1818, in gl_draw
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\viewports.camera", line 1855, in render
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\editortools.player", line 792, in drawToolReticle
KeyError: 'Player'
Press RETURN or close this window to dismiss.

**Comment by LaChal** [comment]
MCEdit can't find the player 'Player' (single game player) in the dimension you want to move it.

The log you posted shows another error: `Caught value error while getting player info for 1377740d-e96d-3851-89b2-9cf6091ac3d8`.

Try to refresh the player names to see if the error still raises.

The full console output may be usefull to track what happens.

**Comment by Monkey0x9** [comment]
Also notice that the UUID is not from a permium minecraft account: http://mcuuid.net/?q=1377740d-e96d-3851-89b2-9cf6091ac3d8

**Comment by LaChal** [comment]
@Monkey0x9: I have some of non-premium UUIDs in some of the world I uses, and I don't experience this issue.
But who ever knows...

**Comment by naor2013** [comment]
If it still happen,  can you please send us your map?

**Comment by Khroki** [comment]
No response, assuming resolved, Reopen and post if it isn't resolved.

**Comment by juozaspo** [comment]
Got a crash a **very similar** to the report above, latest MCedit version crashing, selecting any player on single player world and trying to use "move" it. Dunno if regression, or an old bug. I'm stumped
```
Starting MCEdit...
Running in portable mode. Support files are stored next to the MCEdit directory.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[   ERROR][      pymclevel.leveldb.py:105]:The binary support for PE 1+ worlds could not be loaded:
[   ERROR][      pymclevel.leveldb.py:106]:/home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: nepavyko atverti bendrojo objekto failo: Toks failas ar aplankas neegzistuoja
[ WARNING][ pymclevel.leveldbpocket.py:32]:Error while trying to import leveldb:
[ WARNING][ pymclevel.leveldbpocket.py:33]:Traceback (most recent call last):
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldbpocket.py", line 29, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    import leveldb as leveldb_mcpe
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldb.py", line 107, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    raise e
[ WARNING][ pymclevel.leveldbpocket.py:33]:OSError: /home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: nepavyko atverti bendrojo objekto failo: Toks failas ar aplankas neegzistuoja
[ WARNING][            mcplatform.py:1258]:Initializing window management...
[ WARNING][            mcplatform.py:1263]:Your desktop environment is not yet supported for window sizing/moving.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Snapshot 15w43c', u'Release 1.10.2', u'Release 1.8.8']
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:947]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 1010, in <module>
    main(sys.argv)
  File "mcedit.py", line 944, in main
    MCEdit.main()
  File "mcedit.py", line 822, in main
    rootwidget.run()
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/root.py", line 233, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 763, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/openglwidgets.py", line 22, in gl_draw_self
    self.gl_draw_viewport()
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/openglwidgets.py", line 28, in gl_draw_viewport
    self.gl_draw()
  File "/home/juozas/MCEdit/MCEdit-Unified/viewports/camera.py", line 1891, in gl_draw
    self.render()
  File "/home/juozas/MCEdit/MCEdit-Unified/viewports/camera.py", line 1928, in render
    ct.drawToolReticle()
  File "/home/juozas/MCEdit/MCEdit-Unified/editortools/player.py", line 844, in drawToolReticle
    self.drawCharacterHead(x + 0.5, y + 0.75, z + 0.5, self.revPlayerPos[dim][self.movingPlayer], dim)
KeyError: 'Player'

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window
```
```
Starting MCEdit...
Running in portable mode. Support files are stored next to the MCEdit directory.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[   ERROR][      pymclevel.leveldb.py:105]:The binary support for PE 1+ worlds could not be loaded:
[   ERROR][      pymclevel.leveldb.py:106]:/home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: nepavyko atverti bendrojo objekto failo: Toks failas ar aplankas neegzistuoja
[ WARNING][ pymclevel.leveldbpocket.py:32]:Error while trying to import leveldb:
[ WARNING][ pymclevel.leveldbpocket.py:33]:Traceback (most recent call last):
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldbpocket.py", line 29, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    import leveldb as leveldb_mcpe
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/leveldb.py", line 107, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    raise e
[ WARNING][ pymclevel.leveldbpocket.py:33]:OSError: /home/juozas/MCEdit/MCEdit-Unified/pymclevel/libleveldb.so: nepavyko atverti bendrojo objekto failo: Toks failas ar aplankas neegzistuoja
[ WARNING][            mcplatform.py:1258]:Initializing window management...
[ WARNING][            mcplatform.py:1263]:Your desktop environment is not yet supported for window sizing/moving.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Snapshot 15w43c', u'Release 1.10.2', u'Release 1.8.8']
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:947]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 1010, in <module>
    main(sys.argv)
  File "mcedit.py", line 944, in main
    MCEdit.main()
  File "mcedit.py", line 822, in main
    rootwidget.run()
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/root.py", line 233, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/widget.py", line 763, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/openglwidgets.py", line 22, in gl_draw_self
    self.gl_draw_viewport()
  File "/home/juozas/MCEdit/MCEdit-Unified/albow/openglwidgets.py", line 28, in gl_draw_viewport
    self.gl_draw()
  File "/home/juozas/MCEdit/MCEdit-Unified/viewports/camera.py", line 1891, in gl_draw
    self.render()
  File "/home/juozas/MCEdit/MCEdit-Unified/viewports/camera.py", line 1928, in render
    ct.drawToolReticle()
  File "/home/juozas/MCEdit/MCEdit-Unified/editortools/player.py", line 844, in drawToolReticle
    self.drawCharacterHead(x + 0.5, y + 0.75, z + 0.5, self.revPlayerPos[dim][self.movingPlayer], dim)
KeyError: u'a9cad505-c471-4a34-abcc-a8d126321b75'

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window  
```

**Comment by LaChal** [comment]
Shall be fixed.
