### ISSUE TITLE
Crashes when switching tools _ Ubuntu 14.04

### ISSUE THREAD

**Issue by xiaoas** [Khroki/MCEdit-Unified#551]
always Crashes when I open a world, switch to chunk control, then switch to another tool
I think it's because I selected nothing in chunk control
debug:
Starting MCEdit...
*** APP DIR: /home/xiaoas/mcedit
Running in fixed mode. Support files are in your Documents folder.
Splash load...
*** MCEDIT DEBUG: file_dialog: mcedit/albow/file_dialogs.pyc
*** MCEDIT DEBUG: directory: mcedit/albow
*** MCEDIT DEBUG: current directory: /home/xiaoas/mcedit
*** Xlib version 0.14 found in user's libraries.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/xiaoas/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Xlib.protocol.request.QueryExtension
None
/home/xiaoas/.minecraft/saves/THE first
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1588]:MCEdit version Unified v1.5.0.0 for Minecraft 1.8/1.9
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 42, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 774, in main
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 629, in main
  File "/tmp/release-master/MCEdit-Unified/albow/root.py", line 168, in run
  File "/tmp/release-master/MCEdit-Unified/albow/root.py", line 271, in run_modal
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 399, in handle_mouse
  File "/tmp/release-master/MCEdit-Unified/albow/widget.py", line 481, in call_handler
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 3335, in mouse_down
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 3362, in selectTool
  File "/tmp/release-master/MCEdit-Unified/editortools/chunk.py", line 213, in toolDeselected
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 2759, in chunksToSelection
KeyError: 'pop from an empty set'

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window

**Comment by Podshot** [comment]
Whoops, didn't account for that. Committing a fix right now
