### ISSUE TITLE
MCEdit 1.5.0 64-bit Windows - Can't import large (20MB+) schematics (Merging worlds)

### ISSUE THREAD

**Issue by ferret99gt** [Khroki/MCEdit-Unified#553]
I'm attempting to merge several old worlds together. Despite appearing to perform the schematic import, including copying the blocks for many minutes, then on save, relighting the affected chucks, nothing is actually imported.

A rough of the steps I've taken... (Note I close and reopen MCEdit for each world, just to be safe)

1) Loaded old maps in official 1.8.9 client to convert them. I was happy with the result, no issues.
2) Reviewed each of the old maps in MCEdit 1.5, no issues found.
3) Pruned many chunks from the old maps to shrink them down to only include what I want (Though still largeish areas)
4) Checked each map to ensure no issues, still happy with the results.
5) Exported the entirety of each map to a schematic.
5a) Selected the chucks I wanted (All of them, really)
5b) Switched the select tool, which changed the selection to a large block, with height of 256 and large x/y.
5c) Used Export. The progress bar showed an appropriate chuck/block count and seemed successful.
6) Loaded the new world I am importing into and created a large space of new chucks with Flatworld generator.
7) Saved and reloaded everything, confirmed new chucks were good.
8) Attempted to import the largest schema (With all checkboxes marked, i.e. Copy Air, Copy Biomes, etc). After close to 30+ minutes of copying blocks (4 billion plus blocks), MCEdit returns control to me.
9) No visible effect from import, all chucks are still "flatworld"
10) Saved map, waiting a fairly long time for lighting to complete
11) Closed MCEdit and reopened the target map. All chucks are still flatworld, no evidence of import.

I attempted this several times but could not get the import to work. I later tried to smaller of my 3 world import schematics and had the same results.

I have attached the smallest schematic (Roughly 25MB)
[WorldImport.zip](https://github.com/Khroki/MCEdit-Unified/files/76377/WorldImport.zip)

There are also the following error messages that occur when trying to import the schematic:

Running in fixed mode. Support files are in your Documents folder.
Splash load...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\Redact\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.8.9']
None
C:\Users\Redact\AppData\Roaming\.minecraft\saves\creative
Traceback (most recent call last):
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\pymclevel.infiniteworld", line 1184, in loadLevelDat
  File "_nbt.pyx", line 574, in _nbt.load (_nbt.c:11895)
IOError: [Errno 2] No such file or directory: 'c:\\users\\Redact\\appdata\\local\\temp\\tmpvqpe6bschematic\\level.dat_old'
IOError(2, 'No such file or directory')
Canceled
Traceback (most recent call last):
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\pymclevel.infiniteworld", line 1184, in loadLevelDat
  File "_nbt.pyx", line 574, in _nbt.load (_nbt.c:11895)
IOError: [Errno 2] No such file or directory: 'c:\\users\\Redact\\appdata\\local\\temp\\tmplgchymschematic\\level.dat_old'
IOError(2, 'No such file or directory')
Canceled
Traceback (most recent call last):
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\pymclevel.infiniteworld", line 1184, in loadLevelDat
  File "_nbt.pyx", line 574, in _nbt.load (_nbt.c:11895)
IOError: [Errno 2] No such file or directory: 'c:\\users\\Redact\\appdata\\local\\temp\\tmpdbvuyeschematic\\level.dat_old'
IOError(2, 'No such file or directory')
Canceled
Destination:  _Vector(x=3664, y=0, z=-2928)

**Comment by ferret99gt** [comment]
Earlier, it seemed like I couldn't place the Import selection in an area that didn't already have chunks generated. Hence, I generated some flat world. For whatever reason, I'm now able to place the schematic's import box in "no chunk" space. The result is that MCEdit very quickly displays it's "Copying x blocks" dialogue and within a second closes it, again with no visible changes to the world.

The difference in this method is that the "Copy" is over almost instantly, while copying over existing chunks takes 15+ minutes. The result appears to be the same though.

The same error message about a level.dat_old occurs in this case.

**Comment by codewarrior0** [comment]
Try importing the pruned world directly instead of exporting to a schematic and importing.

It looks like exporting very large schematics (using an alternate file format) is broken.

**Comment by ferret99gt** [comment]
Apologies. I feel like a complete idiot, as I did not even realize Import worked directly on level.dat files, rather than just schematics. It's been a few years.

For the record, MCEdit was able to import the level.dat with no issue.

**Comment by robske110** [comment]
So the BUG is: Schematics are broken

**Comment by EBTheHero** [comment]
For me it works fine...
