### ISSUE TITLE
MCEdit crashes on enter

### ISSUE THREAD

**Issue by 24680FPIC** [Khroki/MCEdit-Unified#563]
MCEdit always crashed when I open the .exe file. Can you help with any advice?
Full text:

Running in fixed mode. Support files are in your Documents folder.
Splash load...
Minecraft_Server.jar storage initialized.
Each server in stored in a subdirectory of C:\Users\[NAME]\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers: []
None
mcedit.main MCEdit exited with errors.
[   ERROR][                              root.py:1601:MCEdit version Unified v1.5.0.0 for Minecraft 1.8/1.9
[   ERROR][                              root.py:1601:"['white']" is not in list
Traceback (most recent call last):
    File "<string>", line 774, in main
    File "<string>", line 515, in main
    File "<string>", line 197, in ___init___
    File "<string>", line 250, in reloadEditor
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\leveleditor", line 300,  in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\leveleditor", line 1001, inreloadToolbar
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 297, in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 65, in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 58, in updateColors
ValueError: "['white']" is not in list
Press RETURN or close this window to dismiss.

Traceback (most recent call last):
    File "<string>", line 837, in <module>
    File "<string>", line 774, in main
    File "<string>", line 515, in main
    File "<string>", line 197, in ___init___
    File "<string>", line 250, in reloadEditor
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\leveleditor", line 300,  in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\leveleditor", line 1001, inreloadToolbar
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 297, in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 65, in __init__
    File "C:\build\bin\build\mcedit\out00-PYZ.pyz\editortools.select", line 58, in updateColors
ValueError: "['white']" is not in list

==================================
                                                         MCEdit has crashed
==================================
Press the Enter key to close this window

**Comment by 24680FPIC** [comment]
Didn't fix...

**Comment by naor2013** [comment]
It's fixed for the next version that will come out soon
