### ISSUE TITLE
MCEdit crash while holding w and then pressing Ctrl when the world is open

### ISSUE THREAD

**Issue by juozaspo** [Khroki/MCEdit-Unified#608]
MCEdit-Unified on Linux Crash with python error _AttributeError: 'NoneType' object has no attribute 'blockAt'_ while the world is open and mouse focus is on a generated chunk

Python 2.7.10
MCEdit-Unified updated to v1.5.1.0/latest version using git
Full log:
```
Starting MCEdit...
[   ERROR][          pymclevel.nbt.py:639]:Failed to import Cythonized nbt file. Running on (very slow) pure-python nbt fallback.
[   ERROR][          pymclevel.nbt.py:640]:(Did you forget to run 'setup.py build_ext --inplace'?)
[   ERROR][          pymclevel.nbt.py:641]:No module named _nbt
[ WARNING][            mcplatform.py:1167]:Initializing window management...
[ WARNING][            mcplatform.py:1172]:Your desktop environment is not yet supported for window sizing/moving.
[   ERROR][                  root.py:1004]:MCEdit version Unified v1.5.1.0 %s Minecraft 1.8/1.9 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 1064, in <module>
    main(sys.argv)
  File "mcedit.py", line 1001, in main
    MCEdit.main()
  File "mcedit.py", line 845, in main
    rootwidget.run()
  File "/home/juozas/MCEdit-Unified/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/juozas/MCEdit-Unified/albow/root.py", line 282, in run_modal
    clicked_widget.handle_mouse('mouse_drag', event)
  File "/home/juozas/MCEdit-Unified/albow/widget.py", line 400, in handle_mouse
    self.call_handler(name, event)
  File "/home/juozas/MCEdit-Unified/albow/widget.py", line 482, in call_handler
    return method(*args)
  File "/home/juozas/MCEdit-Unified/viewports/camera.py", line 1561, in mouse_drag
    self.mouse_move(evt)
  File "/home/juozas/MCEdit-Unified/viewports/camera.py", line 1619, in mouse_move
    showCommands()
  File "/home/juozas/MCEdit-Unified/viewports/camera.py", line 1598, in showCommands
    block = self.editor.level.blockAt(*point)
AttributeError: 'NoneType' object has no attribute 'blockAt'
Running in fixed mode. Support files are in your Documents folder.
Splash load...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Snapshot 15w43c', u'Release 1.8.8']
mcedit.main MCEdit exited with errors.

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this windowPress any key to close.
```

**Comment by naor2013** [comment]
It seems like you press Ctrl when you're near a command block (Maybe...)
Try just Clicking Ctrl over the command blocks you have, if you have any (Without holding W) and tell me if the issue still happens
btw, Are you using the newest build or 1.5.1.0?

**Comment by naor2013** [comment]
Never mind, I figured out the issue, it's fixed

**Comment by juozaspo** [comment]
Thanks.
