### ISSUE TITLE
Crash on Startup 1.5.2.1

### ISSUE THREAD

**Issue by RoiEXLab** [Khroki/MCEdit-Unified#648]
Since I updated MCEdit Unified to 1.5.2.1 it Crashes after shotly popping up. here is the error Message:

```
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[   ERROR][          pymclevel.nbt.py:639]:Failed to import Cythonized nbt file.
 Running on (very slow) pure-python nbt fallback.
[   ERROR][          pymclevel.nbt.py:640]:(Did you forget to run 'setup.py buil
d_ext --inplace'?)
[   ERROR][          pymclevel.nbt.py:641]:DLL load failed: %1 ist keine zulõssi
ge Win32-Anwendung.
[ WARNING][            mcplatform.py:1182]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\Robin\Documents\MCEdit\Serve
rJarStorage named with the server's version number
Cached servers:  []
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.2.1 %s Mi
necraft 1.8/1.9 | PE 0.11
[   ERROR][                  root.py:1009]:'ascii' codec can't encode character
u'\xfc' in position 27: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 1003, in main
  File "<string>", line 734, in main
  File "<string>", line 256, in __init__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 27:
 ordinal not in range(128)
Press RETURN or close this window to dismiss.

Traceback (most recent call last):
  File "<string>", line 1066, in <module>
  File "<string>", line 1003, in main
  File "<string>", line 734, in main
  File "<string>", line 256, in __init__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 27:
 ordinal not in range(128)

==================================
                          MCEdit has crashed
==================================
Press the Enter key to close this window
```

I though, this would be easy to resolved using notepad++ or whatever, but because root.py is not downloaded with the .exe installer this could get a little more complicated...

I would appreciate it very much if someone could fix this issue

**Comment by LaChal** [comment]
This issue is related to #644, and has already been fixed in our code.

All you can do, is to run the program in English (or French) for now...

Or edit your language resource file (in `lang` MCEdit sub-folder) and replace the line starting with 't949' by 't949&nbsp; '. Pay attention to the trailing space, and ensure before editing, that your editor will preserve the UTF-8 encoding and all blank lines and trailing spaces. Notepad++ can do that :smile:
The result shall look like this:

```text
[...]
o948 Menu
t948 
o949 for
t949 
o950 MCEdit does not support window resolutions below 1000x700.
[...]
```

It is not visible in the code snippet, but lines 't948' and 't949' have a space at their end :wink:

**Comment by RoiEXLab** [comment]
Thanks!
