### ISSUE TITLE
Windows, doesn't start

### ISSUE THREAD

**Issue by robske110** [Khroki/MCEdit-Unified#651]
Running in fixed mode. Support files are in your Documents folder.
Splash load...
FEHLER: Der angegebene Registrierungsschlüssel bzw. Wert wurde nicht gefunden.
[ WARNING][            mcplatform.py:1182]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\Tim_Hartmann\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  []
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.2.1 %s Minecraft 1.8/1.9 | PE 0.11
[   ERROR][                  root.py:1009]:Attempt to call an undefined function glWindowPos2d, check for bool(glWindowPos2d) before calling
Traceback (most recent call last):
  File "<string>", line 1003, in main
  File "<string>", line 729, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\utilities.gl_display_context", line 25, in __init__
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\utilities.gl_display_context", line 105, in reset
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\OpenGL.platform.baseplatform", line 407, in __call__
NullFunctionError: Attempt to call an undefined function glWindowPos2d, check for bool(glWindowPos2d) before calling
Press RETURN or close this window to dismiss.

WIndows 10 Pro 64Bit

**Comment by robske110** [comment]
Nevermind, looks like graphic driver issue (i should look at errors first, before i report them, huh?)
