### ISSUE TITLE
MCEdit crashes immediately after launching

### ISSUE THREAD

**Issue by awesomebing1** [Khroki/MCEdit-Unified#656]
Hello!

**Steps to Reproduce**: Unzip downloaded file anywhere (tested user applications folder, Downloads, and Desktop). Right click on file, hit open, and hit "Open" after GateKeeper asks you if you want to run it. You'll then be greeted with the following: 
![mcedit Error (Open Console) (Terminate)](https://cloud.githubusercontent.com/assets/10055256/14944662/f43cd876-0fbf-11e6-9da3-4c6762c80e10.png)

**MCEdit Version Number**: v1.5.2.1
**Operating System Version**: OS X El Capitan 10.11.4
**Error log**:
```
[    INFO][                  config.py:36]:Loading config...
[   DEBUG][                 config.py:194]:Property Change:        Settings                  hiddable ores = [7, 16, 15, 21, 73, 14, 56, 153]
[   DEBUG][                 config.py:194]:Property Change:        Settings                  Recent Worlds = ['']
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          white = (1.0, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           blue = (0.75, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          green = (0.75, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                            red = (1.0, 0.75, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           teal = (0.75, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           pink = (1.0, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                         yellow = (1.0, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           grey = (0.6, 0.6, 0.6)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          black = (0.0, 0.0, 0.0)
[    INFO][OpenGL.acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x107a7d8f0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x107a7d770>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x107a7d8f0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x107a7d770>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
 ```

It looks as if there's no error, right? Let's run it from the terminal, maybe we'll get an error there.
```
imac:~ me$ ~/Downloads/mcedit.app/Contents/MacOS/mcedit
May  1 17:15:41  mcedit[36104] <Notice>: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
May  1 17:15:42  mcedit[36104] <Notice>: Splash load...
May  1 17:15:42  mcedit[36104] <Notice>: 2016-05-01 17:15:42.845 mcedit[36104:599989] 17:15:42.845 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
May  1 17:15:44  mcedit[36104] <Notice>: Traceback (most recent call last):
May  1 17:15:44  mcedit[36104] <Notice>:   File "/Users/me/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:     _run()
May  1 17:15:44  mcedit[36104] <Notice>:   File "/Users/m/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
May  1 17:15:44  mcedit[36104] <Notice>:     exec(compile(source, path, 'exec'), globals(), globals())
May  1 17:15:44  mcedit[36104] <Notice>:   File "/Users/me/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 73, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:     import keys
May  1 17:15:44  mcedit[36104] <Notice>:   File "keys.pyc", line 4, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:   File "albow/__init__.pyc", line 14, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:   File "albow/shell.pyc", line 5, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:   File "albow/root.pyc", line 23, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:   File "pymclevel/__init__.pyc", line 7, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:
May  1 17:15:44  mcedit[36104] <Notice>:   File "pymclevel/items.pyc", line 92, in <module>
May  1 17:15:44  mcedit[36104] <Notice>:
May  1 17:15:44  mcedit[36104] <Notice>:   File "pymclevel/items.pyc", line 34, in __init__
May  1 17:15:44  mcedit[36104] <Notice>:
May  1 17:15:44  mcedit[36104] <Notice>: Exception: Couldn't find Item Files. Please reinstall MCEdit!
May  1 17:15:44  mcedit[36104] <Notice>: 2016-05-01 17:15:44.940 mcedit[36104:599989] mcedit Error
May  1 17:15:46  mcedit[36104] <Notice>: Error in atexit._run_exitfuncs:
May  1 17:15:46  mcedit[36104] <Notice>: Traceback (most recent call last):
May  1 17:15:46  mcedit[36104] <Notice>:   File "atexit.pyc", line 24, in _run_exitfuncs
May  1 17:15:46  mcedit[36104] <Notice>:   File "version_utils.pyc", line 54, in save
May  1 17:15:46  mcedit[36104] <Notice>: AttributeError: PlayerCache instance has no attribute '_cache'
May  1 17:15:46  mcedit[36104] <Notice>: Error in sys.exitfunc:
May  1 17:15:46  mcedit[36104] <Notice>: Traceback (most recent call last):
May  1 17:15:46  mcedit[36104] <Notice>:   File "atexit.pyc", line 24, in _run_exitfuncs
May  1 17:15:46  mcedit[36104] <Notice>:   File "version_utils.pyc", line 54, in save
May  1 17:15:46  mcedit[36104] <Notice>: AttributeError: PlayerCache instance has no attribute '_cache'
imac:~ me$
```

There's the real error we're looking for.

I hope this helps you figure out the error, please ask if you need any other information to solve it!

**Comment by Khroki** [comment]
Try deleting your player cache, it should be with the other mcedit configuration files in mcedit's application folder.

**Comment by Khroki** [comment]
Looking at this further, it can't seem to find the item files, by any chance did you rename the mcedit app?

**Comment by Khroki** [comment]
Looking at it more closely it's not finding the item files, does your username have any non-latin characters in it? Also have you attempted to redownload? The package may have been damaged.

**Comment by awesomebing1** [comment]
I have reloaded. No, my username (which I'd prefer not to give out) contains A-Z letters, no numbers. Excuse me for not trying your original solution, I will try that as soon as I can.

**Comment by Khroki** [comment]
I can't seem to reproduce this issue on the build OSX, which is also 10.11.4 and with the only dependency being xquartz I'm not sure where its going wrong :/. could you maybe take a screenshot of the mcedit folder after extraction?

**Comment by awesomebing1** [comment]
I will as soon as I get home. My fileshstem is case sensitive, might that be part of the problem?

**Comment by Khroki** [comment]
Reopening as I believe the cache error is only half the problem here.

**Comment by awesomebing1** [comment]
Not all Macs have case sensitive filesystems. The default filesystem on a Mac is case-insensitive. Some applications do not support case-sensitive filesystems (e.g Steam).

Here's the contents of `ls mcedit.app/Contents/Resources`:
```
LICENSE.txt		__boot__.py		folder.png		lang			site.pyc		stock-brushes		terrain.png
LR5_mzu.fot		__error__.sh		fonts			lib			site.pyo		stock-filters		toolicons
PythonApplet.icns	char.png		gui.png			mcedit.ico		splash			stock-schematics
RELEASE-VERSION.json	favicon.png		include			mcedit.py		splash.png		terrain-classic.png
TRANSLATION.txt		file.png		items			pymclevel		splashes		terrain-pocket.png
```

I also did a `ls -R mcedit.app/Contents/Resources` on the application. The content is a lot to copy here, so I have uploaded the list of files to [GhostBin](https://ghostbin.com/paste/yx7zh).

**Comment by Khroki** [comment]
Ah yeah I see the problem if your system is case sensitive, the Items folder must be capitalized.

**Comment by awesomebing1** [comment]
I renamed the folder, and it worked. Thank you!

I guess that means in https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/items.py#L31 `itemsdir = os.path.join(directories.getDataDir(), "Items")` needs to be changed to `itemsdir = os.path.join(directories.getDataDir(), "items")`. (I don't know your code that well, so I don't know if that would affect anything.)

**Comment by Khroki** [comment]
Well, renaming the folder and renaming any calls to it would fix it, but I just changed the build script to capitalize the folder properly on build since it works fine on Win and Linux as it is. At any rate glad it's resolved.
