### ISSUE TITLE
Crash on OS X in file browser

### ISSUE THREAD

**Issue by jespertheend** [Khroki/MCEdit-Unified#683]
Every time I close the 'users' folder in the file browser (using 'open' in the start screen) I get a crash.
I'm on OS X 10.11.3 (15D21)
and on MCEDIT-Unified v1.5.3.0

If you have any other questions, let me know

Here's the last part of my system.log
```

May 29 19:08:15 --- last message repeated 1 time ---
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: Splash load...
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.11.3. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
	Call location:
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 0   CarbonCore                          0x00007fff9c546c9b ___Gestalt_SystemVersion_block_invoke + 113
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 1   libdispatch.dylib                   0x00007fff9111833f _dispatch_client_callout + 8
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 2   libdispatch.dylib                   0x00007fff91118237 dispatch_once_f + 67
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 3   CarbonCore                          0x00007fff9c4d2b47 _Gestalt_SystemVersion + 987
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 4   CarbonCore                          0x00007fff9c4d1ddb Gestalt + 139
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 5   SDL                                 0x0000000109023d38 SDL_SoftStretch + 14284
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 6   SDL                                 0x0000000109019627 SDL_VideoInit + 531
May 29 19:08:15 Jespers-Mac-Pro coreaudiod[188]: SecTaskLoadEntitlements failed error=22
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 19:08:15.815 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
May 29 19:08:15 Jespers-Mac-Pro mcedit[2259]: 2016-05-29 19:08:15.816 mcedit[2259:89105] 19:08:15.815 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
May 29 19:08:16 Jespers-Mac-Pro mcedit[2259]: [ WARNING][      pymclevel.BOParser.py:16]:The `bo3.def` file is missing in `/Applications/mcedit.app/Contents/Resources`. The BO3 support will not be complete...
May 29 19:08:16 Jespers-Mac-Pro mcedit[2259]: [ WARNING][            mcplatform.py:1184]:Initializing window management...
May 29 19:08:16 Jespers-Mac-Pro mcedit[2259]: Minecraft_Server.jar storage initialized.
May 29 19:08:16 Jespers-Mac-Pro mcedit[2259]: Each server is stored in a subdirectory of /Users/jesper/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
May 29 19:08:16 Jespers-Mac-Pro mcedit[2259]: Cached servers:  []
May 29 19:08:20 Jespers-Mac-Pro launchservicesd[78]: SecTaskLoadEntitlements failed error=22
May 29 19:08:35 --- last message repeated 1 time ---
May 29 19:08:35 Jespers-Mac-Pro mdworker[2274]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=x86_64}
May 29 19:09:37 Jespers-Mac-Pro mcedit[2259]: *** MCEDIT DEBUG: file_dialog: /Applications/mcedit.app/Contents/Resources/lib/python2.7/site-packages.zip/albow/file_dialogs.pyc
May 29 19:09:37 Jespers-Mac-Pro mcedit[2259]: *** MCEDIT DEBUG: directory: /Applications/mcedit.app/Contents/Resources/lib/python2.7/site-packages.zip/albow
May 29 19:09:37 Jespers-Mac-Pro mcedit[2259]: *** MCEDIT DEBUG: current directory: /Applications/mcedit.app/Contents/Resources
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: mcedit.main MCEdit exited with errors.
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: [   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.3.0 %s Minecraft 1.8/1.9 | PE 0.11
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: Traceback (most recent call last):
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/mcedit.py", line 1066, in <module>
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/mcedit.py", line 1003, in main
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/mcedit.py", line 847, in main
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/root.pyc", line 168, in run
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/root.pyc", line 303, in run_modal
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 400, in handle_mouse
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 482, in call_handler
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/controls.pyc", line 240, in mouse_up
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 482, in call_handler
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/file_opener.pyc", line 144, in promptOpenAndLoad
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "mcplatform.pyc", line 250, in askOpenFile
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "mcplatform.pyc", line 248, in _askOpen
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/file_dialogs.pyc", line 534, in request_old_filename
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 546, in present
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/root.pyc", line 271, in run_modal
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 400, in handle_mouse
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/widget.pyc", line 482, in call_handler
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/tree.pyc", line 129, in mouse_down
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/scrollpanel.pyc", line 234, in mouse_down
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/palette_view.pyc", line 144, in mouse_down
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/grid_view.pyc", line 49, in mouse_down
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/palette_view.pyc", line 194, in click_cell
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/tree.pyc", line 118, in click_item
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/tree.pyc", line 474, in click_item
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/file_dialogs.pyc", line 298, in deploy
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/tree.pyc", line 465, in deploy
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/file_dialogs.pyc", line 301, in select_item
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "albow/tree.pyc", line 480, in select_item
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: IndexError: list index out of range
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: Traceback (most recent call last):
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:     _run()
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:     exec(compile(source, path, 'exec'), globals(), globals())
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:   File "/Applications/mcedit.app/Contents/Resources/mcedit.py", line 1081, in <module>
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]:     raw_input("Press the Enter key to close this window")
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: EOFError: EOF when reading a line
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: ==================================
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: 			  MCEdit has crashed
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: ==================================
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: mcedit Error
May 29 19:09:50 Jespers-Mac-Pro mcedit[2259]: 2016-05-29 19:09:50.687 mcedit[2259:89105] mcedit Error
May 29 19:09:52 Jespers-Mac-Pro sharedfilelistd[248]: SecTaskLoadEntitlements failed error=22
May 29 19:09:52 Jespers-Mac-Pro loginwindow[95]: -[SFLListManager(ServiceReplyProtocol) notifyChanges:toListWithIdentifier:] Notified of item changes to list with identifier com.apple.LSSharedFileList.RecentApplications
May 29 19:09:52 Jespers-Mac-Pro Console[2281]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable
May 29 19:09:52 Jespers-Mac-Pro mcedit[2259]: Press the Enter key to close this window
 
```

**Comment by LaChal** [comment]
Did you experienced this issue on prior MCEdit versions?

Did you select a `level.dat` file from a Minecraft world folder?

**Comment by jespertheend** [comment]
As far as I know the last time I used MCEdit it still had the native OS X browser.
I did not select a level.dat, I just closed the 'users' folder using the arrow next to it.

**Comment by LaChal** [comment]
The last time the OSX file choser was used it was in the release 1.3.1.0, in March 2015...
Looks look you did not updated MCEdit for a while :stuck_out_tongue_winking_eye:

**Comment by jespertheend** [comment]
Haha yes that's right, I haven't played minecraft in a long time :)
