### ISSUE TITLE
corrupted world?

### ISSUE THREAD

**Issue by arliben** [Khroki/MCEdit-Unified#685]
every time I try to load for editing (or even look at it in the selection too long) I get this error. Any help would be appreciated!

Unhandled Exception

Traceback (most recent call last):
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 747, in editWorldFromList (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorapp.py", line 698, in loadFile (self is a MCEditApp)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 362, in __init__ (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 670, in setConfiguredBlocks (self is a EditorSession)
  File "c:\Users\Rio\Documents\mcedit2-distrib\buildbot\winslave-64\winbuild-x64\build\src\mcedit2\editorsession.py", line 674, in reloadModels (self is a EditorSession)
  File "mcedit2\rendering\blockmodels.pyx", line 224, in mcedit2.rendering.blockmodels.BlockModels.__init__ (src/mcedit2/rendering/blockmodels.c:4878)  
    result = self.loadResourceVariant(resourcePath, resourceVariant)
  File "mcedit2\rendering\blockmodels.pyx", line 410, in mcedit2.rendering.blockmodels.BlockModels.loadResourceVariant (src/mcedit2/rendering/blockmodels.c:7653)  
    variantDict = variants[resourceVariant]
KeyError: u'attached=false,facing=south,powered=false,suspended=false'

**Comment by Khroki** [comment]
This is a mcedit 2 error, this is the mcedit 1.x repo. You should go to their repository at https://github.com/mcedit/mcedit2 for help with it.
