### ISSUE TITLE
After upgrade to MCEU v1.5.3.0 on Linux x64, Crash After Chunk Gen

### ISSUE THREAD

**Issue by EvilSupahFly** [Khroki/MCEdit-Unified#687]
Every single time, after using the chunk generator, when I click on something else, for example, "Import Schematic", MCEU crashes with the following error:

```
[   ERROR][                   root.py:777]:MCEdit version Unified v1.5.3.0 %s Minecraft {mc_versions} | PE {pe_versions}
Traceback (most recent call last):
  File "mcedit.py", line 837, in <module>
    main(sys.argv)
  File "mcedit.py", line 774, in main
    MCEdit.main()
  File "mcedit.py", line 629, in main
    rootwidget.run()
  File "/home/seann/mcedit-unified/mcedit/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/seann/mcedit-unified/mcedit/albow/root.py", line 271, in run_modal
    mouse_widget.handle_mouse('mouse_down', event)
  File "/home/seann/mcedit-unified/mcedit/albow/widget.py", line 399, in handle_mouse
    self.call_handler(name, event)
  File "/home/seann/mcedit-unified/mcedit/albow/widget.py", line 481, in call_handler
    return method(*args)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 3335, in mouse_down
    self.selectTool(toolNo)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 3362, in selectTool
    self.parent.currentTool.toolDeselected()
  File "/home/seann/mcedit-unified/mcedit/editortools/chunk.py", line 213, in toolDeselected
    self.editor.chunksToSelection()
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 2759, in chunksToSelection
    starting_chunk = self.selectedChunks.pop()
KeyError: 'pop from an empty set'

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window
```

And in Chunk Mode, I can no longer see the high-level world, just the grid pattern for the chunks, as if they were chunks filled with air instead - I've attached a couple screenshots for that. One shows the world in Camera Mode, one in Chunk Mode.

I'd offer to show you the mcedit.log file but I ran it with debug on, and it's nearly 300,000 lines long.

![screenshot from 2016-06-11 18-51-30](https://cloud.githubusercontent.com/assets/3280846/15987824/9e5f7d80-3005-11e6-977c-3ceb013d9716.png)

Any ideas?
![screenshot from 2016-06-11 18-38-21](https://cloud.githubusercontent.com/assets/3280846/15987804/280ef14c-3005-11e6-983a-83ea19a4395e.png)

**Comment by LaChal** [comment]
I can't reproduce this using 1.8 or 1.8.8 generator...

What is the game version you used to generate the chunks?
How much chunks did you create?

**Comment by EvilSupahFly** [comment]
Minecraft 1.10 - the area was a square, 768 blocks by 768 blocks, or 2,304 chunks.

I tried with both the new 1.10 server and with the Flatland generator.

I'm also seeing a lot of this in the log file when I run MCEdit in debug mode:

```
Traceback (most recent call last):
  File "/home/seann/mcedit-unified/mcedit/renderer.py", line 3717, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/seann/mcedit-unified/mcedit/renderer.py", line 3698, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/seann/mcedit-unified/mcedit/renderer.py", line 383, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/seann/mcedit-unified/mcedit/renderer.py", line 862, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/seann/mcedit-unified/mcedit/renderer.py", line 1550, in makeChunkVertices
    flatcolors[..., :3] *= heightfactor[:, numpy.newaxis, numpy.newaxis]
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
```

I just don't know if it's related because I don't know enough about Python to step through the source in a debugger and watch the output.

I double checked my Pip environment to be sure there wasn't an update I'm missing and all the requirements are met.

**Comment by LaChal** [comment]
Looks like your numpy Python module is not the required version for MCEdit.

The version of some modules can be found near the top of the log file.

Running the Linux installer (from your `/tmp` folder to avoid overriding you actual install) will check the dependencies. It won't install anything, unless you tell it to do so. (And nothing will be installed system wide, only for the user.)

**Comment by EvilSupahFly** [comment]
Pip reports the following versions:
```
PyOpenGL (3.1.0)
numpy (1.9.3)
pygame (1.9.1release)
PyYAML (3.11)
Pillow (3.2.0)
ftputil (3.3.1)
Cython (0.24)
boost 1.58.0 mcpe
```
Since I'm running Ubuntu, I double-checked my system dependencies:
```
seann@black-beast:~/mcedit_v2 $ sudo apt-get install python-opengl python-pygame python-yaml python-numpy python-xlib
[sudo] password for seann: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-numpy is already the newest version.
python-numpy set to manually installed.
python-yaml is already the newest version.
python-yaml set to manually installed.
python-opengl is already the newest version.
python-pygame is already the newest version.
python-xlib is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

If numpy is the wrong version, what version should it be?

**Comment by Khroki** [comment]
Not sure why it's acting up but your pillow version is too new, we only fully support up to version 2.9.

**Comment by EvilSupahFly** [comment]
I'll change that out and see what happens. :)

Any chance the min and max supported version numbers could be added to the documentation?

**Comment by EvilSupahFly** [comment]
Replaced Pillow with v2.9.0 and everything seems to be back to normal

**Comment by Khroki** [comment]
That's good, I should really update that since even the from-source install directions are out of date now.

**Comment by EvilSupahFly** [comment]
Groovy =)

**Comment by EvilSupahFly** [comment]
OK... I may have spoken too soon:

```
seann@black-beast:~/mcedit-unified/mcedit $ python mcedit.py -debug
Running in fixed mode. Support files are in your Documents folder.
Splash load...
*** MCEDIT DEBUG: file_dialog: /home/seann/mcedit-unified/mcedit/albow/file_dialogs.pyc
*** MCEDIT DEBUG: directory: /home/seann/mcedit-unified/mcedit/albow
*** MCEDIT DEBUG: current directory: /home/seann/mcedit-unified/mcedit
*** Xlib version 0.14 found in system's libraries.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
None
/home/seann/.minecraft/saves/Flatland Song World
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
Generating XXX chunks out of 768 starting from (-28, 4)
Generating XXX chunks out of 693 starting from (-26, -3)
Generating XXX chunks out of 672 starting from (0, -26)
Generating XXX chunks out of 600 starting from (-15, -26)
Generating XXX chunks out of 549 starting from (-6, 37)
Generating XXX chunks out of 480 starting from (22, -27)
Generating XXX chunks out of 370 starting from (36, 11)
Generating XXX chunks out of 301 starting from (-28, 34)
Generating XXX chunks out of 229 starting from (-27, -28)
Generating XXX chunks out of 173 starting from (18, 37)
Generating XXX chunks out of 100 starting from (-26, 26)
Generating XXX chunks out of 80 starting from (37, 30)
Generating XXX chunks out of 45 starting from (37, 1)
Generating XXX chunks out of 15 starting from (37, -8)
[ WARNING][                   root.py:830]:Error reading chunk: (-31, -10)
[ WARNING][                   root.py:830]:Error reading chunk: (-32, 1)
[ WARNING][                   root.py:830]:Error reading chunk: (-32, -13)
[ WARNING][                   root.py:830]:Error reading chunk: (-33, -13)
[ WARNING][                   root.py:830]:Error reading chunk: (-31, -10)
[ WARNING][                   root.py:830]:Error reading chunk: (-32, 1)
[ WARNING][                   root.py:830]:Error reading chunk: (-32, -13)
[ WARNING][                   root.py:830]:Error reading chunk: (-33, -13)
[ WARNING][                   root.py:830]:Error reading chunk: (-31, -10)
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:777]:MCEdit version Unified v1.5.3.0 %s Minecraft {mc_versions} | PE {pe_versions}
Traceback (most recent call last):
  File "mcedit.py", line 837, in <module>
    main(sys.argv)
  File "mcedit.py", line 774, in main
    MCEdit.main()
  File "mcedit.py", line 629, in main
    rootwidget.run()
  File "/home/seann/mcedit-unified/mcedit/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/seann/mcedit-unified/mcedit/albow/root.py", line 271, in run_modal
    mouse_widget.handle_mouse('mouse_down', event)
  File "/home/seann/mcedit-unified/mcedit/albow/widget.py", line 399, in handle_mouse
    self.call_handler(name, event)
  File "/home/seann/mcedit-unified/mcedit/albow/widget.py", line 481, in call_handler
    return method(*args)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 3335, in mouse_down
    self.selectTool(toolNo)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 3362, in selectTool
    self.parent.currentTool.toolDeselected()
  File "/home/seann/mcedit-unified/mcedit/editortools/chunk.py", line 213, in toolDeselected
    self.editor.chunksToSelection()
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 2759, in chunksToSelection
    starting_chunk = self.selectedChunks.pop()
KeyError: 'pop from an empty set'

==================================
			  MCEdit has crashed
==================================
```

**Comment by Podshot** [comment]
That crash is from a feature I added that converts chunk selections made with the Chunk Tool to a regular selection box. I thought I added a check to make sure chunk were selected before trying to convert them, but either I forgot to commit it, or it's not working in this situation. I'm currently away from my development environment, so if someone could make a fix, that would be great. If not, I'll do it in about a week.

**Comment by LaChal** [comment]
What I can see in the current code is there are two lines right before the crashing `starting_chunk = self.selectedChunks.pop()` one (`leveleditor.py#2759`):

    if len(self.selectedChunks) == 0:
         return

If you don't have them, you can simply add them, or update you source install.

**Comment by EvilSupahFly** [comment]
It seems to be OK when generating chunks, but when I reload after it's done, I'm still getting the "Pop" error, and when it reloads, some chunks are missing, and when I close the world, and go back to the main menu, I am unable to open a world without first shutting down the editor, and relaunching.

Terminal log:
```
seann@black-beast:~/mcedit-unified/mcedit $ python mcedit.py -debug
Running in fixed mode. Support files are in your Documents folder.
Splash load...
*** MCEDIT DEBUG: file_dialog: /home/seann/mcedit-unified/mcedit/albow/file_dialogs.pyc
*** MCEDIT DEBUG: directory: /home/seann/mcedit-unified/mcedit/albow
*** MCEDIT DEBUG: current directory: /home/seann/mcedit-unified/mcedit
*** Xlib version 0.14 found in system's libraries.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
None
/home/seann/.minecraft/saves/1_9_4 Debug Test World
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
Generating XXX chunks out of 648 starting from (17, 17)
Generating XXX chunks out of 477 starting from (-3, 1)
Generating XXX chunks out of 35 starting from (7, -15)
Generating XXX chunks out of 7 starting from (-14, -15)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "/home/seann/mcedit-unified/mcedit/mceutils.py", line 56, in _alertException
    return func(*args, **kw)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 1325, in reload
    self.loadFile(filename)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 1177, in loadFile
    self.loadLevel(level)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 1211, in loadLevel
    self.toolbar.selectTool(0)
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 3364, in selectTool
    self.parent.currentTool.toolDeselected()
  File "/home/seann/mcedit-unified/mcedit/editortools/chunk.py", line 213, in toolDeselected
    self.editor.chunksToSelection()
  File "/home/seann/mcedit-unified/mcedit/leveleditor.py", line 2759, in chunksToSelection
    starting_chunk = self.selectedChunks.pop()
KeyError: 'pop from an empty set'
[   ERROR][                   root.py:432]:Failed to load file /home/seann/.minecraft/saves/1_9_4 Debug Test World: KeyError('pop from an empty set',)
[   ERROR][                   root.py:432]:Failed to load file /home/seann/.minecraft/saves/Debug Test World: KeyError('pop from an empty set',)
```
![screenshot from 2016-06-15 13-27-32](https://cloud.githubusercontent.com/assets/3280846/16090671/82977ffc-32fe-11e6-887d-2630c870733d.png)

**Comment by LaChal** [comment]
Did you add the lines or updated you install?

The error is exactly the same, on the same line in the same file...

**Comment by EvilSupahFly** [comment]
I did make the change. It gave me a start up error the first time I ran it because I didn't indent the second line properly but started fine after I fixed the indent. When I get home, I'll do a fresh GIT pull to a new directory, add those two lines and try again.

**Comment by EvilSupahFly** [comment]
I actually already have those two lines at 2764 and 2765 so it seems I added them in the wrong place (at 2759) when they didn't need to be there.

Now I feel stupid...

**Comment by Podshot** [comment]
Could you send us your save folder for this world? It may help us in debugging what is causing this issue

**Comment by EvilSupahFly** [comment]
Sure! As soon as I'm home again after work, I'll send you a dropbox link.

**Comment by EvilSupahFly** [comment]
I don't know if this is related, but the Chunk Generator is inconsistent on existing worlds.

It was supposed to fill in the selected area, but as you can see, I got less than satisfactory results. In the terminal, I see this:

```
Each server is stored in a subdirectory of /home/seann/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.10', u'Release 1.09.4', u'Release 1.09.2', u'Release 1.09.0', u'Release 1.08.90', u'Release 1.08.81', u'Release 1.08.80', u'Release 1.08.7', u'Release 1.08.3', u'Release 1.08.1', u'Release 1.08', u'Release 1.07.10', u'Release 1.07.9', u'Release 1.07.5', u'Release 1.07.4', u'Release 1.07.2', u'Release 1.06.4', u'Release 1.06.2', u'Release 1.05.2', u'Release 1.05.1', u'Release 1.05', u'Release 1.04.7', u'Release 1.04.6', u'Release 1.04.5', u'Release 1.04.4', u'Release 1.04.3', u'Release 1.04.2', u'Release 1.04.1', u'Release 1.04', u'Release 1.03.2', u'Release 1.03.1', u'Release 1.03', u'Release 1.02.5', u'Release 1.02', u'Release 0.9-pre6', u'Release 0.9-pre5', u'Release 0.9-pre4', u'Release 0.9-pre3', u'Release 0.9-pre2', u'Release 0.9-pre', u'Release 0.8-pre2', u'Release 0.8-pre', u'RC2', u'13w47e']
Generating XXX chunks out of 3969 starting from (14, 5)
Generating XXX chunks out of 3377 starting from (43, 18)
Generating XXX chunks out of 3370 starting from (-13, -7)
Generating XXX chunks out of 2773 starting from (-6, 43)
Generating XXX chunks out of 2723 starting from (-9, -18)
Generating XXX chunks out of 2433 starting from (-19, 19)
Generating XXX chunks out of 1919 starting from (-19, 4)
Generating XXX chunks out of 1790 starting from (19, 37)
Generating XXX chunks out of 1657 starting from (17, 43)
No chunks were generated. Aborting.
[ WARNING][                   root.py:838]:Error reading chunk: (7, 5)
[ WARNING][                   root.py:838]:Error reading chunk: (11, 5)
[ WARNING][                   root.py:838]:Error reading chunk: (-5, 3)
[ WARNING][                   root.py:838]:Error reading chunk: (13, 5)
[ WARNING][                   root.py:838]:Error reading chunk: (-9, 13)
[ WARNING][                   root.py:838]:Error reading chunk: (16, 12)
[ WARNING][                   root.py:838]:Error reading chunk: (17, 9)
[ WARNING][                   root.py:838]:Error reading chunk: (-11, -1)
[ WARNING][                   root.py:838]:Error reading chunk: (6, 19)
[ WARNING][                   root.py:838]:Error reading chunk: (-12, 5)
[ WARNING][                   root.py:838]:Error reading chunk: (19, 9)
[ WARNING][                   root.py:838]:Error reading chunk: (22, 22)
[ WARNING][                   root.py:838]:Error reading chunk: (-11, -17)
[ WARNING][                   root.py:838]:Error reading chunk: (7, 26)
[ WARNING][                   root.py:838]:Error reading chunk: (27, -2)
[ WARNING][                   root.py:838]:Error reading chunk: (27, 8)
[ WARNING][                   root.py:838]:Error reading chunk: (27, 25)
[ WARNING][                   root.py:838]:Error reading chunk: (-21, 7)
[ WARNING][                   root.py:838]:Error reading chunk: (-21, -2)
[ WARNING][                   root.py:838]:Error reading chunk: (-21, -9)
[ WARNING][                   root.py:838]:Error reading chunk: (-21, -16)
[ WARNING][                   root.py:838]:Error reading chunk: (28, 2)
[ WARNING][                   root.py:838]:Error reading chunk: (28, 25)
[ WARNING][                   root.py:838]:Error reading chunk: (17, -21)
[ WARNING][                   root.py:838]:Error reading chunk: (22, -21)
[ WARNING][                   root.py:838]:Error reading chunk: (29, -14)
[ WARNING][                   root.py:838]:Error reading chunk: (29, 30)
[ WARNING][                   root.py:838]:Error reading chunk: (16, 30)
[ WARNING][                   root.py:838]:Error reading chunk: (-22, 30)
[ WARNING][                   root.py:838]:Error reading chunk: (-23, -14)
[ WARNING][                   root.py:838]:Error reading chunk: (30, 29)
[ WARNING][                   root.py:838]:Error reading chunk: (-24, -15)
[ WARNING][                   root.py:838]:Error reading chunk: (-1, -23)
[ WARNING][                   root.py:838]:Error reading chunk: (-26, 4)
[ WARNING][                   root.py:838]:Error reading chunk: (-26, -16)
[ WARNING][                   root.py:838]:Error reading chunk: (-27, 4)
[ WARNING][                   root.py:838]:Error reading chunk: (-28, 28)
[ WARNING][                   root.py:838]:Error reading chunk: (-28, -19)
[ WARNING][                   root.py:838]:Error reading chunk: (-28, -20)
[ WARNING][                   root.py:838]:Error reading chunk: (-28, -21)
[ WARNING][                   root.py:838]:Error reading chunk: (-30, 30)
[ WARNING][                   root.py:838]:Error reading chunk: (-30, -28)
[ WARNING][                   root.py:838]:Error reading chunk: (-30, -29)
```

![screenshot from 2016-06-18 02-32-48](https://cloud.githubusercontent.com/assets/3280846/16169470/dbc2a9ca-34fd-11e6-9482-f825f4609afa.png)

**Comment by EvilSupahFly** [comment]
Sorry - having trouble signing in to DropBox. Link is coming though.

**Comment by EvilSupahFly** [comment]
Here are two versions of the same world. In the first version, I deleted all the chunks and had MCEdit rebuild them, resulting in the picture in my last post.

The second version is that same world, but after I ran MLG to fill in the missing areas using the same server .JAR that MCEdit calls.

Before MLG, using MCEdit and the official, vanilla 1.10 server .JAR: https://www.dropbox.com/s/4li44xocj11459a/000_Test.rar?dl=0
After MLG using the same server .JAR: https://www.dropbox.com/s/z5jkmo2uq77durp/000_Test_MLG.rar?dl=0

No mods. Pure Vanilla. Side note: when creating a new world in MCEdit, the "Name this new world" dialog box doesn't go away after I click "SAVE".

**Comment by Khroki** [comment]
Just noticed this issue, but the missing random chunks bug on world gen is a very old bug and is directly tied to system load/performance, if the system has a lot running (Especially VMs) more chunks will be MIA, we're still not exactly sure why this is at this time.
