### ISSUE TITLE
MCEdit Error - Mac

### ISSUE THREAD

**Issue by DUELS133** [Khroki/MCEdit-Unified#703]
When I try to open the MCEdit he gives: mcedit Error and displays two options: Open Console and Terminate.
How do I fix this?
![print-mcediterror](https://cloud.githubusercontent.com/assets/6560796/17219839/416eed12-54c3-11e6-910f-3fed8638aec8.png)

**Comment by LaChal** [comment]
We need more information.

The MCEdit version, you OS version, the application and system logs (the part concerning MCEdit) will be usefull to kwon what happends.

**Comment by DUELS133** [comment]
OS El Capitan (10.11.2)
MCEdit Unified 1.5.3.0

28/07/16 15:39:44,120 mcedit[5885]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
28/07/16 15:39:54,123 mcedit[5885]: Splash load...
28/07/16 15:40:07,033 mcedit[5885]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.2 instead of 10.11.2. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
28/07/16 15:40:07,196 mcedit[5885]: 0   CarbonCore                          0x964a7913 ___Gestalt_SystemVersion_block_invoke + 135
28/07/16 15:40:07,196 mcedit[5885]: 1   libdispatch.dylib                   0x97552763 _dispatch_client_callout + 50
28/07/16 15:40:07,196 mcedit[5885]: 2   libdispatch.dylib                   0x9755263f dispatch_once_f + 78
28/07/16 15:40:07,196 mcedit[5885]: 3   libdispatch.dylib                   0x97553ec9 dispatch_once + 31
28/07/16 15:40:07,196 mcedit[5885]: 4   CarbonCore                          0x96423576 _Gestalt_SystemVersion + 1047
28/07/16 15:40:07,196 mcedit[5885]: 5   CarbonCore                          0x964226a5 Gestalt + 154
28/07/16 15:40:07,196 mcedit[5885]: 6   SDL                                 0x036cf21d SDL_SoftStretch + 14808
28/07/16 15:40:10,201 mcedit[5885]: 15:40:10.200 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
28/07/16 15:40:10,201 mcedit[5885]: 2016-07-28 15:40:10.200 mcedit[5885:113767] 15:40:10.200 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
28/07/16 15:40:10,762 mcedit[5885]: Traceback (most recent call last):
28/07/16 15:40:10,762 mcedit[5885]:   File "/Users/*****/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
28/07/16 15:40:10,789 mcedit[5885]:     _run()
28/07/16 15:40:10,789 mcedit[5885]:   File "/Users/*****/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
28/07/16 15:40:10,789 mcedit[5885]:     exec(compile(source, path, 'exec'), globals(), globals())
28/07/16 15:40:10,789 mcedit[5885]:   File "/Users/*****/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 13, in <module>
28/07/16 15:40:10,801 mcedit[5885]:     import splash
28/07/16 15:40:10,801 mcedit[5885]:   File "splash.pyc", line 28, in <module>
28/07/16 15:40:10,801 mcedit[5885]: pygame.error: File is not a Windows BMP file
28/07/16 15:40:11,596 mcedit[5885]: mcedit Error
28/07/16 15:40:11,596 mcedit[5885]: 2016-07-28 15:40:11.596 mcedit[5885:113767] mcedit Error

**Comment by LaChal** [comment]
Thanks.

Look in the .app if there is a file called `splash.png` file.
If not, please reinstall MCEdit.

If the file is there, replace it with another PNG file (500x200 pixels is enough).
If the file is not there, just put one.
There are several types of PNG formats, so you may have to try with few files.

If the error occur again, but the five last lines of the log you sent are different (especially if the fourth line from the end shows a different line number), edit or create the file `splash` in the .app and leave it empty.
This error is the same as the ones encountered by OSX 1.6 users. The fact is the neede libraries for 1.6 are not supported for later version.
We tried to change the images format, but we could not find a satisfactory solution.

MCEdit is compiled on OSX with the 1.9 libraries, AFAIK, and shall work on 10.11+...

Please, report here, even if you could fix :smile:

**Comment by DUELS133** [comment]
It did not work I tried to reinstall MCEdit, but still the same.

**Comment by Khroki** [comment]
Try the latest release and let us know if it's still a problem
