### ISSUE TITLE
Windows 10 Edition (PE 1.15.7) MCEdit:1.5.4.1

### ISSUE THREAD

**Issue by MinecraftWhiz04** [Khroki/MCEdit-Unified#720]
MCEdit can't copy and paste anything in a PE world.

CMD:

Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.4.1
[ WARNING][            mcplatform.py:1276]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\(MyName)\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  []
Clipping:  _Vector(x=1, y=1, z=1)
C:\Users\(MyName)\Desktop\MINECR~1\McEdit\mcedit\renderer.py:1115: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 1
Clipping:  _Vector(x=656, y=128, z=1008)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1175, in copySelection
  File "editortools\select.py", line 1212, in _copySelection
  File "albow\extended_widgets.py", line 360, in showProgress
  File "albow\widget.py", line 549, in present
  File "albow\root.py", line 233, in run_modal
  File "albow\widget.py", line 790, in gl_draw_all
  File "albow\widget.py", line 797, in gl_draw_all
  File "albow\widget.py", line 358, in draw_all
  File "albow\extended_widgets.py", line 276, in draw
  File "pymclevel\schematic.py", line 1067, in extractSchematicFromIter
    for i in tempSchematic.copyBlocksFromIter(sourceLevel, newbox, destPoint, entities=entities, biomes=True, first=True, cancelCommandBlockOffset=cancelCommandBlockOffset):
  File "pymclevel\block_copy.py", line 104, in copyBlocksFromIter
    sourceChunk = sourceLevel.getChunk(*srcCpos)
  File "pymclevel\leveldbpocket.py", line 492, in getChunk
    c = self.worldFile.loadChunk(cx, cz, self)
  File "pymclevel\leveldbpocket.py", line 231, in loadChunk
    chunk = PocketLeveldbChunk(cx, cz, world, data)
  File "pymclevel\leveldbpocket.py", line 1006, in __init__
    Entities = loadNBTCompoundList(data[2])
  File "pymclevel\leveldbpocket.py", line 57, in loadNBTCompoundList
    return load(data)
  File "pymclevel\leveldbpocket.py", line 51, in load
    tag = (nbt.load(buf=(d + '\x00\x00\x00\x00')))
  File "_nbt.pyx", line 595, in _nbt.load (_nbt.c:12318)
  File "_nbt.pyx", line 689, in _nbt.load_compound (_nbt.c:13229)
  File "_nbt.pyx", line 696, in _nbt.load_named (_nbt.c:13306)
  File "_nbt.pyx", line 812, in _nbt.load_tag (_nbt.c:14613)
  File "_nbt.pyx", line 711, in _nbt.load_list (_nbt.c:13475)
  File "_nbt.pyx", line 800, in _nbt.load_tag (_nbt.c:14473)
  File "_nbt.pyx", line 660, in _nbt.load_float (_nbt.c:12948)
  File "_nbt.pyx", line 614, in _nbt.read (_nbt.c:12483)
NBTFormatError: NBT Stream too short. Asked for 4, only had 0

**Comment by LaChal** [comment]
We're aware of this error and working on it.

Basically, the data in some chunk(s) is not correct, from MCEdit point of view...

**Comment by L3ice** [comment]
Refrence: #568 
Closing because its duplicated.
