### ISSUE TITLE
MC Edit permission Denied

### ISSUE THREAD

**Issue by FunkayMonkay149** [Khroki/MCEdit-Unified#735]
I recently bought a new laptop and mcedit worked fine on the old one but on the new one its been giving me problems.  If I try to manipulate the world something like this would pop up.

Error during <function deleteBlocks at 0x000000000A5150B8>:IOError(13, 'Permission dennied')
I checked the black log thingy (I don't know much about coding or anything) and this error was in it

IOError:  [Errno 13]  Permission denied:  'c:\\users\\funka\\appdata\\local\\temp\\mcedit_undo\\6584\\tmpakkidsmceditundo\\##MCEDIT.TEMP##\\region\\r.0.-1.mca'

I tried running as an Administrator and that didn't help. This error has happened with EVERY mcedit version I tried. Any additional info need just ask and tell how since I'm not computer savvy.

**Comment by FunkayMonkay149** [comment]
![log](https://cloud.githubusercontent.com/assets/22897612/19456428/637c8cbe-948f-11e6-8d38-20c289c4aede.PNG)
This is a screen shot of the log thingy

**Comment by LaChal** [comment]
A very similar error has been reported on reddit: https://www.reddit.com/r/MCEdit/comments/58oczh/bug_permission_denied_error_13_every_time_i_try/

We already remarked this error on Windows 7 a while ago, but it appeared veru rarely: https://github.com/Khroki/MCEdit-Unified/issues/126

**Comment by LaChal** [comment]
Not for now, badly.
It can be related to Windows or to the Mincraft version you're running.
Is tihs the PC or the Windows 10 one?

**Comment by FunkayMonkay149** [comment]
This is the PC version of minecraft

**Comment by Podshot** [comment]
Can you close out of MCEdit and delete all folders and files in the `'c:\users\funka\appdata\local\temp\mcedit_undo\` folder?

**Comment by FunkayMonkay149** [comment]
When i tried to edit it still gave me the permission denied error and recreated the folder that was deleted from the mcedit_undo folder.

**Comment by MythicalZ10n** [comment]
This is the error I am getting when trying to run MCEdit on Mint

Starting MCEdit...
*** APP DIR: /home/mythicalz10n/MCEDITNEW/mcedit-1.5.4.1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 38, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 13, in <module>
  File "/tmp/release-master/MCEdit-Unified/splash.py", line 5, in <module>
  File "/tmp/release-master/MCEdit-Unified/directories.py", line 243, in <module>
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/mythicalz10n/.mcedit/MCEdit'
Press any key to close.

I posted this in an old post I think, but I checked it and it had been locked, so I don't know if my comment posted or not. Thanks

**Comment by MythicalZ10n** [comment]
Also, when I run the install, it states that I don't have Python 2.7 installed, so I tried installing the latest to see if that fixed anything and no dice.

**Comment by LaChal** [comment]
A screenshot of the installer can be usefull, because I guess it cant find setuptools for Python 2.7 (according to your first message, Python 2.7 is installed).

Does the directory signaled by the 'OSError' exists?
Just remember that files and directory with a dot as first charater in their names are hidden by default.
Check also the rights on you home folder; the error may come from there.

**Comment by PKMWM1** [comment]
Is there any update on this? None of the worlds that I have edited with MCEdit allow me to edit it again. 
Essentially, when I create a new world, I can edit it with MCEdit once. After that, I can't make any changes to the world with MCEdit anymore. Is ther any solution? I have tried deleting all the MCEdit files and re-installing them, so MCEdit must do something to the files.

**Comment by LaChal** [comment]
@PKMWM1 
Please, answer the next questions:

1. What is your operating system?
2. What version of MCEdit is causing you trouble?
3. Does the game can open correctly the affected worlds?
4. Are you trying to run MCEdit with administrator elevation?

@MythicalZ10n 
Any news on your side?

**Comment by PKMWM1** [comment]
1.) Windows 10 64 bit
2.) 1.5.5.0 (As of January 1, 2016, the latest version)
3.) Yes. The game plays the world just fine. As I didn't notice this problem until last night.
4.) If you mean right clicking on the application, and clicking "run as administrator", then yes

On another note, MCEdit works fine on the afflicted worlds on my other laptop which runs windows 8.

**Comment by naor2013** [comment]
@PKMWM1 2017, not 2016! 😁

Just a thought, can you try moving the finder with the map you're trying to open to another location like your desktop and try to open it from there?

**Comment by PKMWM1** [comment]
Yeah, I tried that as well. Thinking that writing to the desktop doesn't require administrative privileges, but I still get the same error.

**Comment by naor2013** [comment]
Can you send a screenshot of the error when it happens with a map located at the desktop?

**Comment by LaChal** [comment]
Hmmm...

Looks like Microsoft screwed something:
https://answers.microsoft.com/en-us/windows/forum/windows_10-security/folder-and-file-permissions-changed-in-windows-10/38bb51a5-8cfb-4349-b635-0fdae1287eb0?page=1
https://answers.microsoft.com/en-us/windows/forum/windows_10-files/document-folders-marked-read-only-after-upgrade-to/4f00d3fe-82b0-4e6d-a92a-f81751aa6f51?auth=1
https://www.cnet.com/forums/discussions/windows-10-changed-all-my-documents-to-read-only/

You may find some clues in these threads.
I bet for changing ownership of some folders...

**Comment by FunkayMonkay149** [comment]
MCedit has suddenly let me edit my worlds again without the error. I did not try to fix the problem in any way, I just stopped using it then came back and start editing a world and it didn't happen. I think I may have had an update on my laptop that fixed the problem.

**Comment by ThePixelatedCactus** [comment]
I tried but my MCEdit still gives his same error, but only function nudgeBlocks
