### ISSUE TITLE
MCEdit Crashes when trying to open world

### ISSUE THREAD

**Issue by beachguycasey31** [Khroki/MCEdit-Unified#744]
I downloaded MCEdit Unified as it is the one I'm used to and know how to use, but when I try to load it by clicking mcedit.exe and the program it's self loads fine, but when I try to load a world I get the error message below and even when I reinstall MCEdit I get the same message, help!

- I'm using Minecraft Launcher version 1.6.70
- I have Java 8 Update 111 both 32 and 64 bit
- I have Java SE Development Kit 8 Update 111 (64 bit)
-----------------------------------------------------------------------------------------------------------------

Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.4.1
[ WARNING][ mcplatform.py:1276]:Initializing window management...
Unclassified minecraft_server.jar found in cache dir. Discovering version number...
Found version Release 1.11
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\Casey\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers: ['Release 1.11']
[ WARNING][ version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/3b9d53e8fc0e40d3955add3f0e24447d"
[ WARNING][ version_utils.py:370]:Error: timed out
[ WARNING][ version_utils.py:374]:Unknown error occurred while trying to get data from URL: https://sessionserver.mojang.com/session/minecraft/profile/97c70c542bac4d30abb668dd40a47dc7
[ WARNING][ version_utils.py:375]:Traceback (most recent call last):
File "version_utils.py", line 363, in _getDataFromURL
File "urllib2.py", line 154, in urlopen
File "urllib2.py", line 431, in open
File "urllib2.py", line 449, in _open
File "urllib2.py", line 409, in _call_chain
File "urllib2.py", line 1240, in https_open
File "urllib2.py", line 1200, in do_open
File "httplib.py", line 1136, in getresponse
File "httplib.py", line 453, in begin
File "httplib.py", line 409, in _read_status
File "socket.py", line 480, in readline
File "ssl.py", line 734, in recv
File "ssl.py", line 621, in read
SSLError: ('The read operation timed out',)

[ WARNING][ version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/1af336cdfa8f4b51b7c6df3649eb866f"
[ WARNING][ version_utils.py:370]:Error: ('_ssl.c:574: The handshake operation timed out',)
[ WARNING][ version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/c384ffa0265148528e1eb69e17ffb58c"
[ WARNING][ version_utils.py:370]:Error: ('_ssl.c:574: The handshake operation timed out',)
[ WARNING][ version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/aec8b57f8f60451797bdfc546c6f1aa8"
[ WARNING][ version_utils.py:370]:Error: ('_ssl.c:574: The handshake operation timed out',)
[ WARNING][ version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/43f6c12cf4e2303d9cdce250837b0fab"
[ WARNING][ version_utils.py:370]:Error: timed out

**Comment by LaChal** [comment]
These messages just tell you the Mojang servers can't be contacted correctly to load your player skin.
It shall not prevent MCEdit to work :smile:

**Comment by beachguycasey31** [comment]
Well it does all it causes MCEdit to stop responding and I have to force close it through Task Manager.

**Comment by LaChal** [comment]
I guess that if you disconnect from Internet before running MCEdit, it won't 'freeze'.
But this is not exactly the solution.

The secure connection to Mojang's site takes too much time and causes the issue.
You may have to set up some proxy settings, or security rule to ensure the server can respond before the 'timed out' error.

**Comment by beachguycasey31** [comment]
It works now that I disconnected from the internet, but it is still showing errors, which I'm guessing won't have an effect on MCEdit.
-------------------------------------------------------------------------------------------------------------------
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.4.1
[ WARNING][            mcplatform.py:1276]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\Casey\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.11']
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/3b9d53e8fc0e40d3955add3f0e24447d"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/97c70c542bac4d30abb668dd40a47dc7"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/b69e04a8308e4db3a479df6a0a286386"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/1af336cdfa8f4b51b7c6df3649eb866f"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/c384ffa0265148528e1eb69e17ffb58c"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/aec8b57f8f60451797bdfc546c6f1aa8"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/43f6c12cf4e2303d9cdce250837b0fab"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/c072fbc66e5e314b90bdfdd72ac6e1e1"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/288c5d2408f731f196718496521354f1"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/91d323f2537a34ffa0bf9fe5480ef52d"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/69cf887bde0c341fa7429413767ed5db"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "mcedit.py", line 708, in fetch_version
  File "release.py", line 54, in fetch_new_version_info
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

An error occurred checking for updates.
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/1af336cdfa8f4b51b7c6df3649eb866f"
[ WARNING][          version_utils.py:370]:Error: [Errno 11001] getaddrinfo failed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/1af336cdfa8f4b51b7c6df3649eb866f"

**Comment by naor2013** [comment]
Does it happen when you try to load any world or just a specific world?

**Comment by beachguycasey31** [comment]
Any world I try to open.

**Comment by LaChal** [comment]
@beachguycasey31 w'eve reworked the code responsible for the players information and skin dowload.
It may not be faster, but MCEdit will load worlds faster.
The player information in the `Player` panel is updated when the connection for this player is closed.
Note that if no data could be retrieved from the server, the names of the players (or their ID) may show a `Server not ready` default message...
