### ISSUE TITLE
Can't open lastest version

### ISSUE THREAD

**Issue by gdavid04** [Khroki/MCEdit-Unified#770]
I try to open mcedit, but it won't open.
`Traceback (most recent call last):
  File "mcedit.py", line 13, in <module>
  File "C:\build\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "splash.py", line 5, in <module>
  File "C:\build\pyinstaller-develop\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "directories.py", line 225, in <module>
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 14: ordinal not in range(128)
Failed to execute script mcedit`

**Comment by LaChal** [comment]
I guess you have non English characters  in your %APPDATA% folder name.

Can you try to install MCEdit for a user which has only English characters in its name and retry?

Can you tell us if you used former version of MCEdit?
If yes, did you encounter this error?

**Comment by gdavid04** [comment]
Solved the problem, thx
