### ISSUE TITLE
UnicodeDecodeError - V2.0.0 Beta 6

### ISSUE THREAD

**Issue by BunnyWarlord** [Khroki/MCEdit-Unified#772]
An error occurred while opening C:/Users/User/AppData/Roaming/.minecraft/saves/The Halberd/level.dat
'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 201, in __init__ (self is a EditorSession)
  File "mceditlib\worldeditor.py", line 233, in __init__ (self is a WorldEditor)
  File "mceditlib\findadapter.py", line 62, in findAdapter  
  File "mceditlib\anvil\adapter.py", line 463, in __init__ (self is a AnvilWorldAdapter)
  File "mceditlib\anvil\adapter.py", line 530, in loadMetadata (self is a AnvilWorldAdapter)
  File "src\mceditlib\nbt.pyx", line 569, in mceditlib.nbt.load (src/mceditlib/nbt.c:12098)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)  
  File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 669, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13053)  
  File "src\mceditlib\nbt.pyx", line 786, in mceditlib.nbt.load_tag (src/mceditlib/nbt.c:14277)  
  File "src\mceditlib\nbt.pyx", line 662, in mceditlib.nbt.load_compound (src/mceditlib/nbt.c:12976)  
  File "src\mceditlib\nbt.pyx", line 668, in mceditlib.nbt.load_named (src/mceditlib/nbt.c:13041)  
  File "src\mceditlib\nbt.pyx", line 709, in mceditlib.nbt.load_name (src/mceditlib/nbt.c:13470)  
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 16: invalid start byte

This happens every time I try starting MC Edit. Workarounds?

**Comment by Podshot** [comment]
This is an issue with mcedit2. Please report it [here](https://github.com/mcedit/mcedit2)
