### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Magi1053** [Khroki/MCEdit-Unified#790]
Is MCEdit-Unified supported on terminal servers? 
```
minecraft@Volta:~/mcedit$ ./mcedit.sh
Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Splash load...
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 42, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 1046, in main
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 772, in main
  File "/tmp/release-master/MCEdit-Unified/utilities/gl_display_context.py", line 25, in __init__
  File "/tmp/release-master/MCEdit-Unified/utilities/gl_display_context.py", line 51, in reset
error: OpenGL not available

==================================
                          MCEdit has crashed
==================================
Press the Enter key to close this window
```

**Comment by Magi1053** [comment]
Using https://github.com/mcedit/pymclevel
