### ISSUE TITLE
[BUG] [WARNING] Running from source on Linux Mint will break Mintinstall

### ISSUE THREAD

**Issue by Tsoccerguy3** [Khroki/MCEdit-Unified#794]
Affects linux Mint KDE 18.1 x64

There is a bug in Pillow that if you follow the steps on the opening page you will corrupt the python libraries required by Mintinstall and Software Manager will no longer work . Good luck trying to find what files get replaced and the changed cfg files .  
https://bugs.launchpad.net/linuxmint/+bug/808907

`Result from running gksu mintinstall

add_categories took 1.234 ms
build_matched_packages took 0.218 ms
add_packages took 6111.321 ms
add_reviews took 1402.498 ms
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
Traceback (most recent call last):
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 1930, in <module>
Application()
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 59, in wrapper
res = func(*arg)
File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 617, in __init__
sans26 = ImageFont.truetype(self.FONT, 26)
File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
return FreeTypeFont(font, size, index, encoding)
File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource`

**Comment by LaChal** [comment]
Sorry for the late answer.

You can try to install the Python dependencies for the user only using `pip` or `easy_install` (provided in the 'setuptools' package).
This will not corrupt you system libraries. This is the way the installer try to install the dependencies.
