### ISSUE TITLE
Problem trying to get MCPE support

### ISSUE THREAD

**Issue by TheNoobster14** [Khroki/MCEdit-Unified#803]
I'm getting this `/usr/bin/ld: cannot find -lleveldb
collect2: 
error: ld returned 1 exit status
error: command 'c++' failed with exit status 1
` when i run this `python setupnx.py build` I am using Ubuntu 16.04. If anyone knows what's wrong please tell me! I can also provide any info needed to know to help.

**Comment by bman92102** [comment]
@TheNoobster14 That isn't the correct PE build support python file. You need to open Terminal in the pymclevel folder, and run python setup_leveldb.py (This is for the new support which is what I assume you are trying to make) 😄

**Comment by LaChal** [comment]
bman92102 is right.

Just use the `setup_leveldb.py` file to compile the new support on Linux.
If you have trouble with that, please report :wink: 

To use this new support, you'll have to create a file and use a command line switch as described [here](https://github.com/Khroki/MCEdit-Unified/issues/779#issuecomment-288840904).

This 'new feature' stuff shall be removed soon and the new PE support will be the default one :smile:

**Comment by TheNoobster14** [comment]
So i did as told, i got to where it starts to load the file but it crashes. I'm trying to load it using the level.dat file. I get this in the console.
```
user@system-8654ab:~/Desktop/MCEdit-Unified$ sudo python mcedit.py --new-features
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[ WARNING][                   root.py:103]:New features mode requested.
[ WARNING][                   root.py:107]:New features list loaded.
[ WARNING][            mcplatform.py:1258]:Initializing window management...
[ WARNING][            mcplatform.py:1261]:Your desktop environment could not be determined. The support for window sizing/moving is not availble.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/user/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.12']
An error occurred checking for updates.
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:935]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 998, in <module>
    main(sys.argv)
  File "mcedit.py", line 932, in main
    MCEdit.main()
  File "mcedit.py", line 810, in main
    rootwidget.run()
  File "/home/user/Desktop/MCEdit-Unified/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/user/Desktop/MCEdit-Unified/albow/root.py", line 233, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "/home/user/Desktop/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/user/Desktop/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/user/Desktop/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/user/Desktop/MCEdit-Unified/albow/widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "/home/user/Desktop/MCEdit-Unified/albow/widget.py", line 763, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "/home/user/Desktop/MCEdit-Unified/albow/openglwidgets.py", line 22, in gl_draw_self
    self.gl_draw_viewport()
  File "/home/user/Desktop/MCEdit-Unified/albow/openglwidgets.py", line 28, in gl_draw_viewport
    self.gl_draw()
  File "/home/user/Desktop/MCEdit-Unified/viewports/camera.py", line 1891, in gl_draw
    self.render()
  File "/home/user/Desktop/MCEdit-Unified/viewports/camera.py", line 1913, in render
    self.updateBlockFaceUnderCursor()
  File "/home/user/Desktop/MCEdit-Unified/viewports/camera.py", line 345, in updateBlockFaceUnderCursor
    100, config.settings.viewMode.get())
  File "/home/user/Desktop/MCEdit-Unified/raycaster.py", line 85, in firstBlock
    block = level.blockAt(*startPos)
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/infiniteworld.py", line 532, in blockAt
    ch = self.getChunk(xc, zc)
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/leveldbpocket.py", line 1991, in getChunk
    c = self.worldFile.loadChunk(cx, cz, self)
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/leveldbpocket.py", line 1676, in loadChunk
    chunk = self._readChunk(cx, cz, world)
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/leveldbpocket.py", line 1559, in _readChunk
    chunk.add_data(terrain=terrain, tile_entities=tile_entities, entities=entities, subchunk=i)
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/leveldbpocket.py", line 2918, in add_data
    k.add_data(subchunk, unpackNibbleArray(a).tostring())
  File "/home/user/Desktop/MCEdit-Unified/pymclevel/leveldbpocket.py", line 2770, in add_data
    raise ValueError("%s: Data does not match the required %s bytes length: %s bytes"%(self.name, self.subdata_length, len(data)))
ValueError: SkyLight: Data does not match the required 4096 bytes length: 0 bytes

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window

```
I don't know what to do to fix this, i hope i did as i was supposed to. All i can say is I Noob also plz help i fan

**Comment by LaChal** [comment]
So, I guess you could compile the PE support.
This crash has been fixed since you got the sources. Just update them!

You shall not need to run as root. It may cause issues when editing worlds, or change their ownership...

By the way MCEdit could not find resources for your desktop environment. Which one it is?

**Comment by TheNoobster14** [comment]
@LaChal It doesn't let me run the program unless i'm using root. Before it did but I don't know why it stopped letting me. How can I change that? Also, what does it mean by desktop environment?

**Comment by LaChal** [comment]
Several desktop environments can be used on Linux, like KDE, Gnome or XFCE.
Currently, MCEdit supports Gnome, Unity, KDE and Cinnamon. Using another environment will not prevent MCEdit to work, but you may have some minor issues with window placement and resizing.

Regarding the root stuff, it may be possible you got or updated the sources using a 'sudo' command.
To change this, you'll have to chack the ownership of you MCEdit folder (`ls -l <the MCEdit folder>`), and eventually change it (`chown -R <your user name> <the MCEdit folder`).
If you're unsure about these commands, google a bit for more complete documentation :wink:

**Comment by TheNoobster14** [comment]
I use Cinnamon, but resizing the window isn't much of an issue for me since i barely move my windows once they are opened. I'll change the root permission also. What about that error message?^

**Comment by LaChal** [comment]
There shall be missing stuff in the definition files for PE support.

I'll check and update.

**Comment by nic96** [comment]
With PE Versions newer than 0.13 I get the following errors when loading a world:
`[ WARNING][                   root.py:816]:Error reading chunk: 'name'
Traceback (most recent call last):
  File "/path/to/MCEdit-Unified/renderer.py", line 3900, in workOnChunk
    for _ in faceInfoCalculator:
  File "/path/to/MCEdit-Unified/renderer.py", line 3882, in calcFacesForChunkRenderer
    for _ in calc:
  File "/path/to/MCEdit-Unified/renderer.py", line 388, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/path/to/MCEdit-Unified/renderer.py", line 849, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/path/to/MCEdit-Unified/renderer.py", line 1447, in makeChunkVertices
    neighbors = self.chunkCalculator.getNeighboringChunks(chunk)
  File "/path/to/MCEdit-Unified/renderer.py", line 883, in getNeighboringChunks
    neighboringChunks[dir] = level.getChunk(cx + dx, cz + dz)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 958, in getChunk
    c = self.worldFile.loadChunk(cx, cz, self)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 590, in loadChunk
    chunk = self._readChunk(cx, cz, world)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 454, in _readChunk
    chunk.add_data(terrain=tr, tile_entities=te, entities=en, subchunk=i)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 1964, in add_data
    )['name']
KeyError: 'name'`

And when trying to save I get:
`[   ERROR][                    root.py:59]:Exception:
Traceback (most recent call last):
  File "/path/to/MCEdit-Unified/mceutils.py", line 53, in _alertException
    return func(*args, **kw)
  File "/path/to/MCEdit-Unified/leveleditor.py", line 1466, in saveFile
    needsRefresh = [c for c in level.allChunks if level.getChunk(*c).dirty]
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 958, in getChunk
    c = self.worldFile.loadChunk(cx, cz, self)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 590, in loadChunk
    chunk = self._readChunk(cx, cz, world)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 454, in _readChunk
    chunk.add_data(terrain=tr, tile_entities=te, entities=en, subchunk=i)
  File "/path/to/MCEdit-Unified/pymclevel/leveldbpocket.py", line 1964, in add_data
    )['name']
KeyError: 'name'`

1.2.10 worlds load fine and it works editing, but because of the errors above I can't save.
