### ISSUE TITLE
MCEdit Error

### ISSUE THREAD

**Issue by hoodhoodihopman** [Khroki/MCEdit-Unified#816]
I'm trying to merge two worlds on MCEdit 2.0.0 Beta 7. Unfortunately, when I open one of the worlds I am greeted with this error:

An error occurred while opening C:/Users/Rob/Desktop/HaljalikaServer (Hal)-2/level.dat
Failed to read PNG file C:\Users\Rob\Desktop\mcedit2-win64-2.0.0-beta7\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 700, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 515, in __init__ (self is a EditorSession)
  File "mcedit2\editorsession.py", line 1439, in __init__ (self is a EditorTab)
  File "mcedit2\worldview\minimap.py", line 152, in __init__ (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 192, in __init__ (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 233, in setDimension (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 259, in createSceneGraph (self is a MinimapWorldView)
  File "mcedit2\worldview\minimap.py", line 161, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\worldview\worldview.py", line 255, in createWorldScene (self is a MinimapWorldView)
  File "mcedit2\rendering\worldscene.py", line 235, in __init__ (self is a WorldScene)(named None)
  File "mcedit2\rendering\players.py", line 141, in __init__ (self is a PlayersNode)(named None)
  File "mcedit2\rendering\players.py", line 37, in __init__ (self is a PlayerNode)(named None)
  File "mcedit2\util\player_server.py", line 153, in getPlayerInfo  
  File "mcedit2\util\player_server.py", line 190, in _getPlayerInfo (self is a PlayerDataCache)
  File "mcedit2\rendering\players.py", line 31, in _callback (self is a PlayerNode)(named None)
  File "mcedit2\rendering\players.py", line 50, in texturePath (self is a PlayerNode)(named None)
  File "mcedit2\util\load_png.py", line 49, in loadPNGFile  
IOError: Failed to read PNG file C:\Users\Rob\Desktop\mcedit2-win64-2.0.0-beta7\MCEdit 2 Files\player_data\skins\0701fdfbd8b94ac98c01657868121ec4.png

Any ideas?

**Comment by Rambo99** [comment]
MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 62 Stepping 4, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 382.05 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 980/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\editortools\generate.py", line 429, in generateClicked (self is a GenerateTool)(named Generate)
  File "mcedit2\editortools\generate.py", line 66, in generate (self is a CityGeneratePlugin)
  File "mcedit2\synth\l_system_plugin.py", line 98, in generateInSchematic (self is a CityGeneratePlugin)
  File "mcedit2\synth\l_system_plugin.py", line 78, in createSymbolList (self is a CityGeneratePlugin)
  File "mcedit2\util\showprogress.py", line 77, in showProgress  
  File "mceditlib\util\progress.py", line 26, in rescaleProgress  
  File "mcedit2\synth\l_system_plugin.py", line 73, in process  
  File "mcedit2\synth\l_system.py", line 133, in applyReplacementsIterated  
TypeError: range() integer end argument expected, got float.

**Comment by gentlegiantJGC** [comment]
This is the repo for MCEdit Unified which is the updated version of 1.0.
Please report bugs for 2.0 on the 2.0 repo found here https://github.com/mcedit/mcedit2
They are two different projects

**Comment by LaChal** [comment]
Right, wrong place...
