### ISSUE TITLE
Issues with latest commit

### ISSUE THREAD

**Issue by neonerz** [Khroki/MCEdit-Unified#819]
@Podshot sorry I misreported in the other issue, while the noise inside the console has reduced, it still seems to happen from time to time. Here's a chunk of it I was able to capture (sorry, I wasn't able to capture the whole thing)

```
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and typ
es
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in
 workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in
calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, c
lasses))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, classes))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in
 calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, incalcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, classes))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, classes))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3897, in workOnChunk
    for _ in faceInfoCalculator:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3879, in  calcFacesForChunkRenderer
    for _ in calc:
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in calcFacesForChunkRenderer
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, classes))
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 861, in
<genexpr>
    blockRenderers.extend(br for br in cr.blockRenderers if not isinstance(br, classes))
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by neonerz** [comment]
I'll keep an eye on it, but it seems as of commit 9507e67 the errors I was seeing have gone away. At least in my limited testing.

**Comment by LaChal** [comment]
Closing, since it's fixed.
