### ISSUE TITLE
Issue on Startup.

### ISSUE THREAD

**Issue by NFGamerMC** [Khroki/MCEdit-Unified#821]
```
C:\Users\nfgam\Desktop\MCEdit-Unified>python mcedit.py
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
DLL load failed: %1 is not a valid Win32 application.
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
[   ERROR][      pymclevel.leveldb.py:105]:The binary support for PE 1+ worlds could not be loaded:
[   ERROR][      pymclevel.leveldb.py:106]:[Error 193] %1 is not a valid Win32 application
[ WARNING][ pymclevel.leveldbpocket.py:32]:Error while trying to import leveldb:
[ WARNING][ pymclevel.leveldbpocket.py:33]:Traceback (most recent call last):
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "C:\Users\nfgam\Desktop\MCEdit-Unified\pymclevel\leveldbpocket.py", line 29, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    import leveldb as leveldb_mcpe
[ WARNING][ pymclevel.leveldbpocket.py:33]:  File "C:\Users\nfgam\Desktop\MCEdit-Unified\pymclevel\leveldb.py", line 107, in <module>
[ WARNING][ pymclevel.leveldbpocket.py:33]:    raise e
[ WARNING][ pymclevel.leveldbpocket.py:33]:WindowsError: [Error 193] %1 is not a valid Win32 application
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using WScript.Shell.SpecialFolders: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Error while getting AppData folder using SHGetSpecialFolderLocation: ImportError('DLL load failed: %1 is not a valid Win32 application.',)
Traceback (most recent call last):
  File "mcedit.py", line 111, in <module>
    import keys
  File "C:\Users\nfgam\Desktop\MCEdit-Unified\keys.py", line 4, in <module>
    import albow
  File "C:\Users\nfgam\Desktop\MCEdit-Unified\albow\__init__.py", line 32, in <module>
    from albow.file_opener import FileOpener
  File "C:\Users\nfgam\Desktop\MCEdit-Unified\albow\file_opener.py", line 9, in <module>
    import mcplatform
  File "C:\Users\nfgam\Desktop\MCEdit-Unified\mcplatform.py", line 114, in <module>
    import win32gui
ImportError: DLL load failed: %1 is not a valid Win32 application.

C:\Users\nfgam\Desktop\MCEdit-Unified>































































































```

**Comment by NFGamerMC** [comment]
@LaChal

**Comment by neonerz** [comment]
Looks like a dll you are using is failing to load. If I were to take a guess, you are using the levelDB-MCPE.dll @LaChal posted in issue #676 . Assuming so, his DLL targeted 64 bit systems, but it seems you need a 32 bit version. I believe the one that comes with the repo is for 32 bit systems.

**Comment by LaChal** [comment]
I complied the PE DLL for 64bit systems, as far as I can remember... I'll check.

The last error let us see it is related to the file opener. Looks like a 32 bit app tries to use 64 bit DLLs, or vice versa...

**Comment by gentlegiantJGC** [comment]
I think I had the same problem. The dll only works with a 64bit version of of the win32 library and thus a 64bit python install.

To start with I had 32bit versions installed and got this error. In my case installing the 64bit version fixed this but a 32 bit alternative should probably be sorted

**Comment by LaChal** [comment]
`win32` is the generic name for some Python/Windows binding libraries.
Actually, two version of `pywin32` are available: the 32bit one and the 64bit one.
I guess `win32` is kept for the library name for compatibility. So, Python programs created on 32bit Python can also run on 64bit Python.
If you install a 32bit Python, install the 32bit version of `win32`; if you also install a 64bit Python, pay attention to install the 64bit `win32` for this 64bit Python.

**Comment by LaChal** [comment]
@NFGamerMC Did you managed to make MCEdit to work?

**Comment by gentlegiantJGC** [comment]
I don't know how this would work when you compile it into an exe but if someone has a 32 bit computer would they be able to use this at all? Might be an idea to compile a 32 bit version and have it select the appropriate one

**Comment by LaChal** [comment]
Indeed.

But the issue here seem to be related to wrong Python installation, since the first invalid Win32 application errors are not related to the PE support, but to the user's temporary folder gathering.
On Windows, we're relying on the underlying system to get various information.

The last win32 related error (which possibly crashed MCEdit) is not related to the PE support too, but to the GUI.

I suspect there's a 32bit Python running on 64bit Windows which may not have 32bit support, or a wrong win32 Python package...
