### ISSUE TITLE
Multiple AttributeError errors ('FakeLevel' object has no attribute '_MCLevel__defs_ids') while generating and simulating new world in mcedit

### ISSUE THREAD

**Issue by juozaspo** [Khroki/MCEdit-Unified#833]
Generating new world and having Simulate world checked produce alot of AttributeError messages. Full log below:
```
Starting MCEdit...
Running in portable mode. Support files are stored next to the MCEdit directory.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[ WARNING][            mcplatform.py:1258]:Initializing window management...
[ WARNING][            mcplatform.py:1263]:Your desktop environment is not yet supported for window sizing/moving.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/juozas/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
scrap not available
No servers found in cache.
Downloading the latest Minecraft Server...
Version: 1.12
Found version  Release 1.12
/home/juozas/MCEdit/MCEdit-Unified/renderer.py:1150: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 1
  return self.precomputedVertices[direction][blockIndices]
No __temp__ file found.
Traceback (most recent call last):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3899, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3881, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 388, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 849, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 1329, in makeChunkVertices
    notMonsters = self.chunkCalculator.level.defsIds.mcedit_defs.get('notMonsters', self.notMonsters)
  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/level.py", line 169, in defsIds
    return self.__defs_ids
AttributeError: 'FakeLevel' object has no attribute '_MCLevel__defs_ids'
Traceback (most recent call last):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3899, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3881, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 388, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 849, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 1329, in makeChunkVertices
    notMonsters = self.chunkCalculator.level.defsIds.mcedit_defs.get('notMonsters', self.notMonsters)
  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/level.py", line 169, in defsIds
    return self.__defs_ids
AttributeError: 'FakeLevel' object has no attribute '_MCLevel__defs_ids'
Traceback (most recent call last):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3899, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3881, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 388, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 849, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 1329, in makeChunkVertices
    notMonsters = self.chunkCalculator.level.defsIds.mcedit_defs.get('notMonsters', self.notMonsters)
  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/level.py", line 169, in defsIds
    return self.__defs_ids
AttributeError: 'FakeLevel' object has no attribute '_MCLevel__defs_ids'
Traceback (most recent call last):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3899, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 3881, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 388, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 849, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/juozas/MCEdit/MCEdit-Unified/renderer.py", line 1329, in makeChunkVertices
    notMonsters = self.chunkCalculator.level.defsIds.mcedit_defs.get('notMonsters', self.notMonsters)
  File "/home/juozas/MCEdit/MCEdit-Unified/pymclevel/level.py", line 169, in defsIds
    return self.__defs_ids
AttributeError: 'FakeLevel' object has no attribute '_MCLevel__defs_ids'
Shutting down...
Press any key to close.
```

**Comment by juozaspo** [comment]
Latest updates appear to fix this problem. closing this now.
