### ISSUE TITLE
Empty Tile Entity Hover Causes Crash

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#837]
```
Traceback (most recent call last):
  File "mcedit.py", line 1010, in <module>
    main(sys.argv)
  File "mcedit.py", line 944, in main
    MCEdit.main()
  File "mcedit.py", line 822, in main
    rootwidget.run()
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\root.py", line 168, in run
    self.run_modal(None)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\root.py", line 233, in run_modal
    self.gl_draw_all(self, (0, 0))
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\widget.py", line 766, in gl_draw_all
    subwidget.gl_draw_all(root, suboffset)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\widget.py", line 763, in gl_draw_all
    self.gl_draw_self(root, offset)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\openglwidgets.py", line 22, in gl_draw_self
    self.gl_draw_viewport()
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\openglwidgets.py", line 28, in gl_draw_viewport
    self.gl_draw()
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\viewports\camera.py", line 1901, in gl_draw
    self.render()
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\viewports\camera.py", line 1928, in render
    self.root.update_tooltip()
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\root.py", line 575, in update_tooltip
    self.show_tooltip(mouse_widget, pos)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\albow\root.py", line 561, in show_tooltip
    ttext = widget.tooltipText
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\viewports\camera.py", line 1698, in tooltipText
    return self.block_info_parsers[block](point)
  File "C:\Users\james_000\Desktop\MCEdit-Unified-master\viewports\camera.py", line 2114, in parse_info
    return "[Empty Container]{}{}".format(self.nbt_ending + self.edit_ending)
IndexError: tuple index out of range

==================================
                          MCEdit has crashed
==================================
Press the Enter key to close this window
```

I think the '+' should be a  ','
making this change to the source code seems to fix the problem

**Comment by LaChal** [comment]
Right.
Dunno why it haven't been fixed before..
