### ISSUE TITLE
PE Worlds with a section sign (§) in the file name fails to load

### ISSUE THREAD

**Issue by neonerz** [Khroki/MCEdit-Unified#843]
This only seems to happen for PE worlds, it doesn't seem to effect Java.

If you attempt to load up a world with a section sign (§) in its name, MCEdit fails with:

```
Traceback (most recent call last):
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\leveleditor.py", line 1186,
 in loadFile
    level = pymclevel.fromFile(filename)
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\pymclevel\mclevel.py", line
 226, in fromFile
    return PocketLeveldbWorld(filename)
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\pymclevel\leveldbpocket.py", line 771, in __init__
    self.worldFile = PocketLeveldbDatabase(filename, self, create=create, world_version=self.world_version)
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\pymclevel\leveldbpocket.py", line 258, in __init__
    with self.world_db() as db:
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\pymclevel\leveldbpocket.py", line 221, in world_db
    self._world_db = self.ldb.DB(self.options, os.path.join(str(self.path), 'db'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 35:
 ordinal not in range(128)
```

**Comment by LaChal** [comment]
Something to do file file name encoding, I guess.

For now, just rename the file with letters and numbers.

**Comment by neonerz** [comment]
commit to fix this worked.
