### ISSUE TITLE
Cant open world

### ISSUE THREAD

**Issue by Quatrosss** [Khroki/MCEdit-Unified#848]
An error occurred while opening C:\Users\quatr\Desktop\ATLauncher\Instances\ResonantRise\saves\New World\level.dat
a float is required

Traceback (most recent call last):
  File "mcedit2\editorapp.py", line 781, in loadFile (self is a MCEditApp)
  File "mcedit2\editorsession.py", line 190, in __init__ (self is a EditorSession)
TypeError: a float is required

**Comment by Quatrosss** [comment]
i cant view my world but cant edit it, it just crashes

**Comment by LaChal** [comment]
You're on the MCEdit-Unified tracker.
We can't do anything here regarding mcedit2 :/

Try https://github.com/mcedit/mcedit2 :smile:
