### ISSUE TITLE
Startup and schematic issues

### ISSUE THREAD

**Issue by mitya12342** [Khroki/MCEdit-Unified#863]
4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 GNU/Linux
Just finished MCEdit.v1.4.0.1.Lin.Universal.run installer
Getting this
```
Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Splash load...
Traceback (most recent call last):
  File "../bin3/mcedit/mcedit.py", line 71, in <module>
  File "../bin3/mcedit/version_utils.py", line 416, in <module>
  File "../bin3/mcedit/version_utils.py", line 79, in load
  File "../bin3/mcedit/version_utils.py", line 51, in __convert
KeyError: 'username'
Press any key to close.
```
When i do "running from source" thing, it runs well except schematic export
Getting this
```
[   ERROR][                    root.py:59]:Exception:
Traceback (most recent call last):
  File "/home/mitya12342/MCEdit-Unified/mceutils.py", line 53, in _alertException
    return func(*args, **kw)
  File "/home/mitya12342/MCEdit-Unified/editortools/select.py", line 1225, in exportSelection
    self.editor.exportSchematic(schematic)
  File "/home/mitya12342/MCEdit-Unified/leveleditor.py", line 843, in exportSchematic
    StructureNBT.fromSchematic(schematic).save(filename)
  File "/home/mitya12342/MCEdit-Unified/pymclevel/schematic.py", line 813, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length), mats=namedMaterials[getattr(schematic, "Materials", 'Alpha')])
  File "/home/mitya12342/MCEdit-Unified/pymclevel/schematic.py", line 737, in __init__
    from materials import blockstateToID
ImportError: cannot import name blockstateToID
```

**Comment by naor2013** [comment]
How exactly are you running from source? This issue was fixed a few days ago so you shouldn't experience it if running from source

**Comment by mitya12342** [comment]
Completely redownloaded all the files, now it works
Sorry for taking your time

**Comment by naor2013** [comment]
It's really ok, we're glad to help!
If you experience any other issues, don't hesitate to report them as well :)
